### ISSUE TITLE
Unable to contact slurm controller

### ISSUE THREAD

**Issue by venkkris** [ArjunaCluster/ArjunaUsers#100]
## Basic Info
Your Name: Venkatesh Krishnamurthy
Your Andrew ID: venkatek

## Where it happened
Job Ids: 60541, 60542, 60564
Node(s) on which the problem occurred: d013, e001, c004

## What Happened
Expected Behavior: python script execution
Observed Behavior: srun: error: Unable to confirm allocation for job 60564: Unable to contact slurm controller (connect failure)
srun: Check SLURM_JOB_ID environment variable. Expired or invalid job 60564

Job Ended at Thu Nov 18 13:38:38 EST 2021
But had to cancel the job. Job status is CG on queue.

## Log Files
Location of Log file Showing the Error: /home/venkatek/CFx/AFx/hBN/fluoride/chair/relax
Location of Script showing [Minimum Working Example]:

> Please also attach any logs and the submission script to this issue.
> If you don't have a log/ bash script, delete the examples below

```log # 'log' here because it's a log file
Submit log files like this (Notice the ``` before and after this block)
this ensures logs are formated correctly (Ie. Comments don't become headings)

```

```bash # 'bash' here it's a bash script
#!/bin/bash
#SBATCH --ntasks 28
#SBATCH --cpus-per-task 1
...

```

[Minimum Working Example]: https://en.wikipedia.org/wiki/Minimal_working_example

## What I've Tried

> List what you've tried to debug the issue, and any commands you've tried
> Include **both** the output of a command **and** the command itself

1) I googled...
2) I looked for similar issues
3) ...

> If you don't have a shell command, delete this example
```shell # 'shell' here because we're showing a shell command
> awesome_command
Output from awesome_command
```

> Thank you for filling out the issue template. We will do our best to help you

**Comment by abillscmu** [comment]
Thanks for reporting, I'm working on it, this might get worse before it gets better.

**Comment by abillscmu** [comment]
Should be resolved
