### ISSUE TITLE
PSC Power Issues

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#106]
## Basic Info
Your Name: Archie
Your Andrew ID: mingzeya

## Where it happened
Job Ids: / 
Node(s) on which the problem occurred: / 

## What Happened
Expected Behavior: show running jobs normally
Observed Behavior: cannot use squeue command to see the jobs: "slurm_load_jobs error: Unable to contact slurm controller (connect failure)"

## Log Files
Location of Log file Showing the Error: / 
Location of Script showing [Minimum Working Example]: /

**Comment by abillscmu** [comment]
Thanks for the report, looks like we've had an unexpected reboot. It will be back momentarily

**Comment by yaomz16** [comment]
seems like hercules cluster has the same issue

**Comment by emilannevelink** [comment]
Is this the same root issue for why all the cpu nodes are down?

**Comment by abillscmu** [comment]
yes

**Comment by abillscmu** [comment]
I'm guessing PSC had a power issue

**Comment by abillscmu** [comment]
Running the restart script, should be fixed In the morning

**Comment by emilannevelink** [comment]
looks like they are still in maintenance.

**Comment by yaomz16** [comment]
Failed again: "slurm_load_jobs error: Unable to contact slurm controller (connect failure)"

**Comment by abillscmu** [comment]
This is actually a new issue. PSC had another power problem :\

**Comment by abillscmu** [comment]
This should be resolved. A couple of nodes are taking a little longer
