### ISSUE TITLE
Jobs stuck on CG status on debug queue

### ISSUE THREAD

**Issue by christianfrech** [ArjunaCluster/ArjunaUsers#108]
## Basic Info
Your Name: Christian Frech
Your Andrew ID: cfrech

## Where it happened
Job Ids: 78634, 78635
Node(s) on which the problem occurred: e001, e002

## What Happened
Expected Behavior: Expected job to complete or be cancelled using scancel
Observed Behavior: Job stuck on CG status for multiple hours, unable to kill using scancel

## Log Files
Location of Log file Showing the Error:
Location of Script showing [Minimum Working Example]:

```bash # 'bash' here it's a bash script
#!/bin/bash
#SBATCH -J sisso_test # Job name
#SBATCH -n 54 # Number of total cores
#SBATCH -N 1 # Number of nodes
#SBATCH -o job_%j.out # File to which STDOUT will be written %j is the job #
#SBATCH -p debug
#SBATCH --time=00:05:00

spack load intel-oneapi-compilers@2021.3.0
spack load intel-mkl@2020.4.304
#spack load libfabric@1.12.1
spack load intel-oneapi-mpi@2021.3.0

echo "Job started on hostname at date"

sisso_path="/home/marom_group/SF/SISSO"


ulimit -s unlimited

mpirun -np 54 $sisso_path &> SISSO.out
...

## What I've Tried

1) Tried scancel, no result
2) Checked existing issues on ArjunaUsers, found identical issue which required node reboot

**Comment by abillscmu** [comment]
Jobs are now cancelled, node will RTS. I think this was caused by the power issues

**Comment by emilannevelink** [comment]
I have the same thing for cpu nodes f004,f005,f018,f022,f002,f003. I cancelled them because the jobs were stuck (no io) after coming back online. I wonder if this is the case for all other jobs that were running when the power issues happened

**Comment by christianfrech** [comment]
This issue has recurred with the same job on the idle node, which has been stuck in the CG state for 1 day
