### ISSUE TITLE
PSC Power Issue Aftermath

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#109]
If an open issue already exists for the node, please do not submit a duplicate!

(Arjuna) Node:  d[008,015],f[008,012], d[010-014,022],f[002-005,009-011,013-014,018,022], c019, c[004,020]
(Hercules) Node: all nodes
Date and Time you first noticed it was down: Jan 6 2021, 10:49am
Anything Else:  seems like the power issue still has a serious effect on our Arjuna and Hercules clusters.

**Comment by mkphuthi** [comment]
Some of the jobs seem to be stuck in CG status, likely a filesystem problem? @yaomz16 are you jobs running at all or are they just stuck?

**Comment by venkkris** [comment]
Having the same issue as Keith's. job.sh.o%j file not being created for running jobs. Tried to cancel them, got the email confirming the cancellation but job status in squeue shows up as CG.

**Comment by abillscmu** [comment]
@mkphuthi are the jobs running or do they just go straight into CG?

**Comment by mkphuthi** [comment]
Nothing happens. The job "runs" in that it takes time but no code is running then when it eventually hits the wall time it goes into CG, has been in CG for days.

**Comment by abillscmu** [comment]
Aight this should be fixed 🤞. For posterity, it was an issue with `firewalld`
