### ISSUE TITLE
Sbatch Error

### ISSUE THREAD

**Issue by danao413** [ArjunaCluster/ArjunaUsers#112]
## Basic Info
Your Name: Dana O'Connor
Your Andrew ID: danao

## Where it happened
Job Ids: N/A
Node(s) on which the problem occurred: all of them

## What Happened
Expected Behavior: "submitted job X"
Observed Behavior: "sbatch: error: Batch job submission failed: Requested node configuration is not available"

## Log Files
Location of Log file Showing the Error:
Location of Script showing [Minimum Working Example]: ran an "echo hello world" command with a slurm script (according to the docs) and got this error

#!/bin/bash
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -n 56
#SBATCH --mem=2G
#SBATCH -A marom
#SBATCH -J test

echo "Hello World!"

```log # 'log' here because it's a log file
Submit log files like this (Notice the ``` before and after this block)
this ensures logs are formated correctly (Ie. Comments don't become headings)

```

```bash # 'bash' here it's a bash script
#!/bin/bash
#SBATCH --ntasks 28
#SBATCH --cpus-per-task 1
...

```

[Minimum Working Example]: https://en.wikipedia.org/wiki/Minimal_working_example

## What I've Tried

Tried googling the error and reading the docs, but the example in the docs threw its own slurm errors...

**Comment by abillscmu** [comment]
2 cores are reserved for system tasks (things like file I/O). The shown example works with `#SBATCH -n 54` rather than `#SBATCH -n 56`.
