### ISSUE TITLE
Update OS to support glibc_2.23

### ISSUE THREAD

**Issue by emilannevelink** [ArjunaCluster/ArjunaUsers#113]
I am trying to use a python package that depends on glibc_2.23, but libm.so.6 doesn't include it on arjuna. 

Just putting this here to show support for an upgrade.

**Comment by abillscmu** [comment]
duly noted

**Comment by kianpu34593** [comment]
@emilannevelink I'm having the same problem here

**Comment by emilannevelink** [comment]
for what it's worth, I was able to fix this inside of a conda environment. I don't know the specifics of how the libraries were referenced, but conda worked and spack didn't
