### ISSUE TITLE
Issue with Data Slots Available

### ISSUE THREAD

**Issue by jboyd23** [ArjunaCluster/ArjunaUsers#114]
> If you notice an issue on arjuna, please first search the existing issues and ensure
> that it has not been reported. If you notice a similar example, please comment on that issue.
>
> Instructions:
> 1) Update the issue's title with something informative
> 2) Fill out the form with request information
> 3) Delete all instructions (Lines that start with `>`) and unused parts of the form
> 4) Submit the issue by clicking "Submit New Issue"
>
> Tips for getting help
> - Quote your shell/log files with backticks. It makes reading them **much** easier
> - Include **both** the output of a command **and** the command itself
> - A minimal working example is a huge plus, we do not debug user code

## Basic Info
Your Name: Jarrett Boyd
Your Andrew ID: jboyd@andrew.cmu.edu

## Where it happened
Job Ids: barepore_current/1.8/bias_0/Seed_2
Node(s) on which the problem occurred:

## What Happened
Expected Behavior: Generation of barepore simulation for Phosphorene biomaterial
Observed Behavior:  Simulation runs for approximately 4 seconds and then fails. 

## Log Files
Location of Log file Showing the Error: /home/jboyd/barepore_current/1.8/bias_0/Seed_2
Location of Script showing [Minimum Working Example]:

> Please also attach any logs and the submission script to this issue.
> If you don't have a log/ bash script, delete the examples below

```bash # 'bash' here it's a bash script
#!/bin/bash
#SBATCH -J cpu_test_0 # Job name
#SBATCH -n 28 # Number of total cores
#SBATCH -N 1 # Number of nodes
#SBATCH -A barati
#SBATCH -p cpu
#SBATCH --mem-per-cpu=2000 # Memory pool for all cores in MB
#SBATCH -e /home/jboyd/barepore_current/1.8/bias_0/Seed_2/1error_lammps.err
#SBATCH -o /home/jboyd/barepore_current/1.8/bias_0/Seed_2/1out_lammps.out
#SBATCH --mail-type=END,FAIL,BEGIN # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=jboyd@andrew.cmu.edu # Email to which notifications will be sent
#SBATCH -t 7-0:00
echo "Job started on `hostname` at `date`"
module load cuda/10.2.89 
module load gcc/11.2.0
spack load libfabric@1.12.1
spack load fftw
mpirun -np 28 /home/jboyd/lammps-29Sep2021/build/lmp_mpi < MIW.in

echo " "
echo "Job Ended at `date`"


[Minimum Working Example]: https://en.wikipedia.org/wiki/Minimal_working_example

## What I've Tried

> List what you've tried to debug the issue, and any commands you've tried
> Include **both** the output of a command **and** the command itself

1)Was originally having a series of library issues. To combat this cleared and reinstalled my lammps program and libraries
2) Manually loaded libraries in the bash file
3) Encountered the above issue. The simulations work while running them on a local machine for tests just fail as soon as I try to run them through arjuna.



> Thank you for filling out the issue template. We will do our best to help you

**Comment by abillscmu** [comment]
It's an issue with "cores" as defined by slurm and mpi. You need to request 2x the number of cores as mpi processes.

see also #54, you may be able to load the intel MPI and fix it

**Comment by jboyd23** [comment]
I updated the bash and doubled the number of cores. Now when I do this and look at my queue it says (ReqNodeNotAvail, UnavailableNodes:d[001,017],f[010,012])

**Comment by awadell1** [comment]
That (ReqNodeNotAvail) will happen if the resources are being consumed by another job. Your job will start when the nodes are released. Although it looks like they also died in ~4 seconds

The permissions on your log files are blocking read access, can you update that? Or upload the files somewhere?
