### ISSUE TITLE
Node Error

### ISSUE THREAD

**Issue by jboyd23** [ArjunaCluster/ArjunaUsers#117]
> If you notice an issue on arjuna, please first search the existing issues and ensure
> that it has not been reported. If you notice a similar example, please comment on that issue.
>
> Instructions:
> 1) Update the issue's title with something informative
> 2) Fill out the form with request information
> 3) Delete all instructions (Lines that start with `>`) and unused parts of the form
> 4) Submit the issue by clicking "Submit New Issue"
>
> Tips for getting help
> - Quote your shell/log files with backticks. It makes reading them **much** easier
> - Include **both** the output of a command **and** the command itself
> - A minimal working example is a huge plus, we do not debug user code

## Basic Info
Your Name: Jarrett Boyd
Your Andrew ID: jboyd

## Where it happened
Job Ids:    MIW.data, MIW.in
Node(s) on which the problem occurred: /home/jboyd/barepore_current/1.8/bias_0/Seed_2

## What Happened
Expected Behavior: Run Simulation
Observed Behavior: Simulation was stuck in queue

## Log Files
Location of Log file Showing the Error: 
Location of Script showing [Minimum Working Example]: /home/jboyd/barepore_current/1.8/bias_0/Seed_2

> Please also attach any logs and the submission script to this issue.
> If you don't have a log/ bash script, delete the examples below

```log # 'log' here because it's a log file
Submit log files like this (Notice the ``` before and after this block)
this ensures logs are formated correctly (Ie. Comments don't become headings)

Bash File:

#!/bin/bash
#SBATCH -J cpu_test_0 # Job name
#SBATCH -n 56 # Number of total cores
#SBATCH -N 1 # Number of nodes
#SBATCH -A barati
#SBATCH -p cpu
#SBATCH --mem-per-cpu=2000 # Memory pool for all cores in MB
#SBATCH -e /home/jboyd/barepore_current/1.8/bias_0/Seed_2/1error_lammps.err
#SBATCH -o /home/jboyd/barepore_current/1.8/bias_0/Seed_2/1out_lammps.out
#SBATCH --mail-type=END,FAIL,BEGIN # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=jboyd@andrew.cmu.edu # Email to which notifications will be sent
#SBATCH -t 7-0:00
echo "Job started on `hostname` at `date`"
module load cuda/10.2.89 
module load gcc/11.2.0
module load mpich/3.4.2   
module load openmpi/4.1.1-paagsgr/fftw/3.3.9
spack load libfabric@1.12.1
spack load fftw
mpirun -np 56 /home/jboyd/lammps-29Sep2021/build/lmp_mpi < MIW.in

echo " "
echo "Job Ended at `date`"

## What I've Tried

Previously I was encountering an error where the terminal couldnt allocate enough resources to run the simulation when I raised that issue I was told to double the number of requested nodes and that should fix my issue. I doubled the requested nodes now I can't even get the simulations to run period to determine if there are any other errors with it. I know the simulations are okay they run on a local machine fine however anytime I try to run anything through arjuna they break. 

> Thank you for filling out the issue template. We will do our best to help you

**Comment by abillscmu** [comment]
you need to use less than 56 cores, since the cpu nodes only have 54 available cores (we reserve 2 for system processes such as I/O. 

Earlier I was referring to the number of mpi processes. 

These changes can be implemented in your job script by changing:
`SBATCH -n 56`
to 
`SBATCH -n 54` 

and 

`mpirun -np 56...`
to 
`mpirun -np 27...`

Although I think the earlier issue resolved this by loading an intel mpi.
