### ISSUE TITLE
Put a succinct title here

### ISSUE THREAD

**Issue by jboyd23** [ArjunaCluster/ArjunaUsers#118]
> If you notice an issue on arjuna, please first search the existing issues and ensure
> that it has not been reported. If you notice a similar example, please comment on that issue.
>
> Instructions:
> 1) Update the issue's title with something informative
> 2) Fill out the form with request information
> 3) Delete all instructions (Lines that start with `>`) and unused parts of the form
> 4) Submit the issue by clicking "Submit New Issue"
>
> Tips for getting help
> - Quote your shell/log files with backticks. It makes reading them **much** easier
> - Include **both** the output of a command **and** the command itself
> - A minimal working example is a huge plus, we do not debug user code

## Basic Info
Your Name: Jarrett Boyd
Your Andrew ID: jboyd

## Where it happened
Job Ids: MIW.in
Node(s) on which the problem occurred:

## What Happened
Expected Behavior: Simulation to run
Observed Behavior: Simulations immediately failed

## Log Files
Location of Log file Showing the Error:  /home/jboyd/barepore_current/1.8/bias_-2/Seed_2
Location of Script showing [Minimum Working Example]: /home/jboyd/barepore_current/1.8/bias_-2/Seed_2

#!/bin/bash
#SBATCH -J cpu_test_0 # Job name
#SBATCH -n 54 # Number of total cores
#SBATCH -N 1 # Number of nodes
#SBATCH -A barati
#SBATCH -p cpu
#SBATCH --mem-per-cpu=2000 # Memory pool for all cores in MB
#SBATCH -e /home/jboyd/barepore_current/1.8/bias_0/Seed_2/1error_lammps.err
#SBATCH -o /home/jboyd/barepore_current/1.8/bias_0/Seed_2/1out_lammps.out
#SBATCH --mail-type=END,FAIL,BEGIN # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=jboyd@andrew.cmu.edu # Email to which notifications will be sent
#SBATCH -t 7-0:00
echo "Job started on `hostname` at `date`"
module load cuda/10.2.89 
module load gcc/11.2.0
module load mpich/3.4.2 
module load openmpi/4.1.1-paagsgr/fftw/3.3.9  
spack load libfabric@1.12.1
spack load fftw
mpirun -np 27 /home/jboyd/lammps-29Sep2021/build/lmp_mpi < MIW.in

echo " "
echo "Job Ended at `date`"
s

#error file
srun: error: spank: x11.so: Plugin file not found
lmp: error while loading shared libraries: libfftw3.so.3: cannot open shared object file: No such file or directory

[Minimum Working Example]: https://en.wikipedia.org/wiki/Minimal_working_example

## What I've Tried: Ive ran the simulations on a local machine and they work fine. I just cant get them to run through arjuna

> I've tried adding the library through spack load
>> spack load libfftw3.so.3

> Thank you for filling out the issue template. We will do our best to help you

**Comment by awadell1** [comment]
Hey @jboyd23

Some quick comments so we can help you more efficiently going forward:

1. Do put a succulent title, it makes it much easier for search for related issues. Ie. "Unable to load libfftw3"
2. The job id should be a number like `77623`. It looks like you put the job name. I can use `sacct` and `squeue` to get more information about the job **if** I have the job id. When you submit the job you should see the id printed to your console.
3. Try to keep issues consolidated. It makes it easier for other users to find information, and easier for us to see what needs fixing. In an ideal world, this would be a new comment on #110

Does that all make sense? If you could go ahead an update the title, that would be awesome!

On to the your issue:

`spack load libfftw3.so.3` is not a valid spack command. Please check out the following docs for more info on using spack:

- https://arjunacluster.github.io/ArjunaUsers/about/user_software.html#spack
- https://spack.readthedocs.io/en/latest/basic_usage.html
- https://spack.readthedocs.io/en/latest/basic_usage.html#spack-load-unload

By the looks of it, I'm guessing you've put a compiled version of lammps at `/home/jboyd/lammps-29Sep2021/build/lmp_mpi`? If so, it looks like an issue with how you've link the libfftw libraries to the executable. I'd review the docs for compiling the lammps and make sure you link to the spack provided libfftw libraries. Regardless, this is an issue with your build system

Alternatively, just install lammps with spack! Check out `spack info lammps` for the build options.
