### ISSUE TITLE
Arjuna is down for scheduled maintenance (Returned to Service)

### ISSUE THREAD

**Issue by abillscmu** [ArjunaCluster/ArjunaUsers#121]
As many users may have noticed, Arjuna has been slow to recover from power outages at PSC lately. To debug these issues, **Arjuna will be down beginning May 9**, for no longer than 1 week.

**Comment by awadell1** [comment]
Arjuna has returned to service. As we have done previously, the max CPUs per user has been limited to 64. We will double this limit in 24 hours and then lift it in 48.
