### ISSUE TITLE
No spack permissions on compute nodes

### ISSUE THREAD

**Issue by mkphuthi** [ArjunaCluster/ArjunaUsers#122]
## Basic Info
Your Name: Keith
Your Andrew ID: mphuthi

## Where it happened
Job Ids: -
Node(s) on which the problem occurred: Any

## What Happened
Expected Behavior: Loading spack modules in interactive or batch mode on the compute nodes
Observed Behavior: Error: `==> Error: [Errno 13] Permission denied: '/home/spack/spack/opt'`

## Log Files
Location of Log file Showing the Error: None 
Location of Script showing [Minimum Working Example]: 

`srun -n 1 --pty bash`
`spack find`

## What I've Tried

Load a spack program in a batch script and interactively

**Comment by awadell1** [comment]
Thanks for the report! It looks like we're missing some of the spack config files in the worker images.
Will have a fix out in the next day or so.

**Comment by yaomz16** [comment]
I have similar issue, when I tried to load quantum espresso with`spack load quantum-espresso` on node f011, the following error bounced back :"Error: [Errno 20] Not a directory: '/home/spack/spack/opt/spack'"

**Comment by awadell1** [comment]
Should be fixed now!
