### ISSUE TITLE
Slurm Error

### ISSUE THREAD

**Issue by emilannevelink** [ArjunaCluster/ArjunaUsers#123]
## Basic Info
Your Name: Emil
Your Andrew ID: eannevel

## Where it happened
Job Ids: 119383
Node(s) on which the problem occurred:

## What Happened
Expected Behavior: Job starts without error
Observed Behavior: Job gives slurmsepd err

```
slurmstepd: error: container_p_join: open failed /scratch/119383/.active: No such file or directory
slurmstepd: error: container_g_join failed: 119383
```

**Comment by mkphuthi** [comment]
Beat me to it by a minute

**Comment by abillscmu** [comment]
we're going back down to figure this out

**Comment by abillscmu** [comment]
we back
