### ISSUE TITLE
Arjuna has Returned to service

### ISSUE THREAD

**Issue by awadell1** [ArjunaCluster/ArjunaUsers#124]
Arjuna will be down for maintenance starting at 9am on 5/23/2022. We plan on being back online by 5/27/2022, preferably sooner.

For more information, see: https://lists.andrew.cmu.edu/mailman/private/arjuna-users/2022-May/000059.html

**Comment by abillscmu** [comment]
Arjuna is down to apply a security patch

**Comment by awadell1** [comment]
Arjuna has returned to service. A temporary limit of 64 CPUs per user has been enabled and will be lifted in 24 hours.
