### ISSUE TITLE
Issue when using quantum-espresso

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#130]
> If you notice an issue on arjuna, please first search the existing issues and ensure
> that it has not been reported. If you notice a similar example, please comment on that issue.
##Basic Info
Your Name: Archie
Your Andrew ID: mingzeya

## Where it happened
Job Ids: /
Node(s) on which the problem occurred: head node

## What Happened
Expected Behavior: / 
Observed Behavior: pw.x: error while loading shared libraries: libpmi2.so.0: cannot open shared object file: No such file or directory

## Log Files
Location of Log file Showing the Error: /
Location of Script showing [Minimum Working Example]:
(on head node)
spack load quantum-espresso
pw.x
then the error bounced out: pw.x: error while loading shared libraries: libpmi2.so.0: cannot open shared object file: No such file or directory. Normally it should be something saying "waiting for input file"

**Comment by abillscmu** [comment]
Please take a look at the documentation for [connecting to arjuna](https://arjunacluster.github.io/ArjunaUsers/getting_started/connecting.html). Other methods of connecting to Arjuna are not supported and are therefore not guaranteed to work.

**Comment by yaomz16** [comment]
oh I solved the problem by installing my own quantum espresso. Sorry that I forgot to close the issue
