### ISSUE TITLE
Resetting Password- Current Password not Accepted

### ISSUE THREAD

**Issue by keyasharma** [ArjunaCluster/ArjunaUsers#131]
## Basic Info
Your Name: Keya Sharma
Your Andrew ID: Keyas

## What Happened
Expected Behavior: Accepts password and gives access to desktop
Observed Behavior: Inputting password to login however it does not accept it. Had set up new password after account creation however currently does not accept auto-generated password that was emailed at account creation nor does it accept the newly set up password.

> List what you've tried to debug the issue, and any commands you've tried

1) I googled how to change password however you can only to it using your previous password. However my previous password isn't being accepted.
2) I looked for similar issues but they were related to the autogenerated password.

Thank you!

**Comment by abillscmu** [comment]
Once you change your password, it won't accept the old password. I'm generating a new password and emailing it to you. You will be required to change your password again on login. Please use [ssh keys](https://arjunacluster.github.io/ArjunaUsers/getting_started/connecting.html) in the future.
