### ISSUE TITLE
GPU jobs fail with no observable reason

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#133]
## Basic Info
Your Name: Archie
Your Andrew ID:

## Where it happened
Job Ids: 126791
Node(s) on which the problem occurred: c022 (but probably all gpu nodes. I also observe similar issue on cpu nodes)

## What Happened
Expected Behavior: running normally
Observed Behavior: gpu jobs (and some cpu jobs) run for around 50 mins and fail. There is no output in the stderr file

## Log Files
Location of Log file Showing the Error: /home/mingzeya/test_gpu_crash/error_126791.err  and  /home/mingzeya/test_gpu_crash/out_126791.out 

Location of Script showing [Minimum Working Example]:   
 /home/mingzeya/test_gpu_crash
where I have a very simple script test.py:
```
import time

while True:
    time.sleep(120)
    print(time.time())
```
and submitted it to gpu nodes using Train.sh

## What I've Tried
I found this issue when I try to train my dp models and found all the training jobs fail after ~50 mins. I then wrote the above test.py which basically does nothing and submitted to gpu nodes, and the same thing happened again. I found similar issue on cpu nodes (you can find a sample job in  /home/mingzeya/test_cpu_crash)

**Comment by abillscmu** [comment]
To be clear, this is happening on GPU and CPU?

**Comment by abillscmu** [comment]
It should happen on every node for all users. Will update this when it's fixed

**Comment by yaomz16** [comment]
> To be clear, this is happening on GPU and CPU?

This is definitely happening on GPU. I'm running a test job on CPU nodes in ```/home/mingzeya/test_cpu_crash``` because I observed similar issue on cpu nodes

**Comment by yaomz16** [comment]
Yep I confirm this is also an issue on the cpu node. Job id 126819 located at ```/home/mingzeya/test_cpu_crash2```. It runs for 5 mins and fails. Another job 126817 located at ```/home/mingzeya/test_cpu_crash``` runs for about 50 mins and fails. I guess the time before it fails is somewhat propotional to the cpu cores that the job requests?

**Comment by abillscmu** [comment]
this is fixed
