### ISSUE TITLE
GPU jobs fail again with no observable reason 

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#134]
## Basic Info
Your Name: Archie
Your Andrew ID:

## Where it happened
Job Ids: 127017
Node(s) on which the problem occurred: c022 (possibly on all gpu nodes)

## What Happened
Expected Behavior:
Observed Behavior: job failed after 8 mins for no reason (same with issue #133)

## Log Files
Location of Log file Showing the Error: /home/mingzeya/test_gpu_crash/error_127017.err
Location of Script showing [Minimum Working Example]:
home/mingzeya/test_gpu_crash
where I have a very simple script test.py:

```
import time

while True:
    time.sleep(120)
    print(time.time())
```
and submitted it to gpu nodes using Train.sh

**Comment by yaomz16** [comment]
seems like cpu nodes don't have this issue now

**Comment by awadell1** [comment]
Our kill bot went a bit rouge. It has been tamed.

Apologies for the inconvenience
