### ISSUE TITLE
Help on installing kubernetes operator on cluster 

### ISSUE THREAD

**Issue by kianpu34593** [ArjunaCluster/ArjunaUsers#136]
## Basic Info
Your Name: jiankun pu
Your Andrew ID: jiankunp

## What Happened

Hi administrators, I want to install [this](https://github.com/dptech-corp/wlm-operator) in the cluster. It's essentially a kubernetes operator that can work with slurm. This will be useful for a project that I want to work on. 

However, I'm a bit confused about this step: 

It's mentioning something called `red-box` here. I cannot find this library/binary in the suggested location. Can I get some help? 

Here is the original instruction: 
Run ./bin/red-box in the background. By default red-box listens on /var/run/syslurm/red-box.sock, you can specify the socket path by -socket, e.g.
```
./bin/red-box -socket /var/run/user/$(id -u)/syslurm/red-box.sock
```

**Comment by awadell1** [comment]
Did you skip step 3: `cd wlm-operator && make`? 

`./bin/red-box` is a relative path so it's not a system executable. Reading the makefile for the project, you def need to make it first. Some relevant docs:

- Page 11 of [Unix for the Beginning Mage](https://dasher.wustl.edu/chem430/readings/unix-tutorial.pdf) has s good overview of paths
- The [docs for make](https://www.gnu.org/software/make/manual/make.html#Overview) are fantastic. Or [my slide deck from way back](https://cmu.box.com/s/nq3rgnyiftmsvvptfnz7p1ffgdj6qjhe)

**Comment by kianpu34593** [comment]
No I didn't. I ran the third step. 
I'm a bit confused about creating not in my directory.
Is this allowed? `/var/run/user/$(id -u)/syslurm/red-box.sock`

**Comment by kianpu34593** [comment]
After running this step, I got this:
<img width="1194" alt="Screen Shot 2022-05-28 at 9 26 15 AM" src="https://user-images.githubusercontent.com/59935793/170804403-6d351540-2a9a-4801-a298-7f72d3acd4bf.png">

**Comment by kianpu34593** [comment]
Update: I created a syslurm dir in the designated path and rerun this:
```
./bin/red-box -socket /var/run/user/$(id -u)/syslurm/red-box.sock
```
The rest of the steps are done in my local machine to setup k8s.
