### ISSUE TITLE
How to load docker image to compute node

### ISSUE THREAD

**Issue by kianpu34593** [ArjunaCluster/ArjunaUsers#138]
Hi adminstrators,

I'm trying an example of using a k8s container on the compute node. 
It's attempting to pull a docker image in the compute node. 
Is this possible? I thought compute node is not connected to the internet.
Is there anyway to copy this image to the compute node and load it while running?

Thank you!

**Comment by awadell1** [comment]
You have access to `/home` or `/tmp` (Need to request space with `--tmp`) on the compute nodes. As far as copying data to the nodes (ie. `/tmp`), `scp`, `rsync` or `sbcast` are your best bets.

Don't you need root privileges to run docker?

**Comment by kianpu34593** [comment]
right, I found that out just earlier lol.
And also, if I understand this correctly, compute node doesn't even have docker right?

How about the singularity? Are we going to support this?

**Comment by awadell1** [comment]
Have you tried using the spack singularity package? (`spack install singularity` or `spack install apptainer`)? From the looks of the docs that's all that needed (ie. we can skip the image update)

I'm rather wary of running docker on the compute nodes. Most of the info I've seen about running untrusted containers requires no bind mounts, but idk if we can programmatically enforce that. Plus with out the bind mounts, getting files into/out of the container would be a beast

Other concerns:
- containers are run by the deamon process. How would we track/restrict compute resources to what was requested?
- Performance-wise singularity/apptainer seems to beat out docker: https://www.diva-portal.org/smash/get/diva2:1277794/FULLTEXT01.pdf
- I really can't overstate how wary I am of providing general access to a docker deamon running as root.

Okay so it looks like rootless mode is a thing: https://docs.docker.com/engine/security/rootless/
- We do have `newuidmap` and `newgidmap` installed in the worker images
- We're missing the right content in `/etc/subuid` but it's mostly there on the headnode. We can probably just copy it over into a runtime overlay (no reboot)

**Comment by abillscmu** [comment]
def try spack first. 

let's stick to singularity for now if possible

**Comment by abillscmu** [comment]
any updates here?

**Comment by abillscmu** [comment]
closed due to inactivity
