### ISSUE TITLE
Calling sbatch from a compute Node

### ISSUE THREAD

**Issue by emilannevelink** [ArjunaCluster/ArjunaUsers#139]
## Basic Info
Your Name: Emil
Your Andrew ID: eannevel

## Where it happened
Job Ids: 128848
Node(s) on which the problem occurred: c023

## What Happened
Expected Behavior: Before the last update, I was able to call `sbatch` from a compute node, but now I get a `File is not found` error. I have tried running `which sbatch` from the head node and during an interactive session and `sbatch` is not on the path when trying to access it from a compute node.

## Log Files
Location of Log file Showing the Error: /home/eannevel/ARPA-E/slabmol/runs/Lislab_EC_0.18_30/logs/output.128848

## What I've Tried

I ran `which sbatch` from the head node and get `/usr/local/bin/sbatch`, but when I run `which sbatch` from the compute node I get:

```
/usr/bin/which: no sbatch in (/home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/miniconda3-4.9.2-et7ujxrrzevxewx65fnmzqkftwwkrsyc/bin:/home/eannevel/bin:/home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/miniconda3-4.9.2-et7ujxrrzevxewx65fnmzqkftwwkrsyc/condabin:/home/spack/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/miniconda3-4.9.2-et7ujxrrzevxewx65fnmzqkftwwkrsyc/bin:/home/eannevel/bin:/home/spack/spack/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/eannevel/github/SU2/bin:/home/eannevel/.local/bin:/home/eannevel/github/SU2/bin)
```
after changing into the `/usr/local/bin` directory from the compute node I don't see a number of the executables that I see from the head node.

1) I looked for similar issues, but it seems tied to the most recent update.

**Comment by abillscmu** [comment]
noted. How critical is this?

**Comment by emilannevelink** [comment]
Not critical. I was going to set-up a work around using a cron job but will probably try what alex recommended

**Comment by emilannevelink** [comment]
Cool, it looks like that works. I didn't want to do that since I didn't want two sbatch's floating around but feel reassured that you suggested it.

**Comment by abillscmu** [comment]
Although based on the weather forecast for tomorrow, it seems likely we might get one anyway

**Comment by abillscmu** [comment]
this is fixed pending a reboot
