### ISSUE TITLE
Spack cannot load Quantum Espresso

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#144]
### Your Name

Archie

### Andrew ID

mingzeya

### Where it Happened

Nodes:d023 interactive job (but I think it is on all cpu nodes)

### What Happened?

when I tried to load quantum espresso using `spack load quantum-espresso@7.0` in the interactive mode, it takes forever to respond `==> Error: Timed out waiting for a write lock.`. For those submitted jobs using Quantum espresso, the output will be like 
"srun: error: spank: x11.so: Plugin file not found
slurmstepd: error: execve(): pw.x: No such file or directory
slurmstepd: error: execve(): pw.x: No such file or directory
..."
you can find one such job at /home/mingzeya/Li_DFT_DP_Gen_project/ML/work/fp/10b77ef2-1a0c-40c3-9a5c-f6ccbdc76d4f/task.003.000000/output

**Comment by yaomz16** [comment]
I tried to load quantum espresso 6.7 instead, but I got the following error `pw.x: error while loading shared libraries: libpmi2.so.0: cannot open shared object file: No such file or directory`

**Comment by mkphuthi** [comment]
You can load it with `spack -L quantum-espresso`. There seems to be a write lock affecting every user for individual QE installs (maybe other packages as well). Not sure of the cause.

**Comment by awadell1** [comment]
Locking is a known issue (https://github.com/spack/spack/issues?q=label%3Alocking+). Unfortunately, the best info I've seen is the `-L` option, but that can get you up a creek if stuff changes on you. The lock is there for a reason after all

As for a more reliable alternative, I'd recommend one of the following:

- Use modules `module load ....`
    - Pros: Way fast, and we have a bunch already setup for you
    - Cons: You have to make new ones for anything you install
    - Docs: https://spack-tutorial.readthedocs.io/en/latest/tutorial_modules.html)
- Use `spack load --sh quantum-espresso > activate_qe.sh` and then `source activate_qe.sh`
    - Pros: No module files, can do things ad-hoc
    - Cons: You need to keep the script up to date, doesn't scale nicely to more packages
- Use Environments: https://spack-tutorial.readthedocs.io/en/latest/tutorial_environments.html
   - Pros: 
       - Creates filesystem view that you just prepend to your path, so even faster!
       - Scales to tons of packages (This is how I manage packages we offer as a base line)
       - Can resolve packages together so they all use the same compiler, version of blas, or whatever
       - You get a nice `spack.yml` that makes it easy to reproduce your environment
   - Cons: New thingy to learn
   
 FWIW: I use modules for things like dev tools, and environments for my compute jobs. I don't use the `spack load --sh` trick.

**Comment by yaomz16** [comment]
Thanks! Let me have a try

**Comment by yaomz16** [comment]
These suggestions work! Thanks
