### ISSUE TITLE
Fatal error in PMPI_Init when running in interactive node

### ISSUE THREAD

**Issue by jtcrystal** [ArjunaCluster/ArjunaUsers#160]
### Your Name

JT Wu

### Andrew ID

jiatian2

### Where it Happened

JobID: 204148 Nodes: d003

### What Happened?

When I tried to run the following command line in an interactive node,
`$ srun -n 54 vasp_ncl > vasp.out`
I immediately got the error message on repeats for many times, 
```
Abort(1091087) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(138): 
MPID_Init(945).......: 
MPIR_pmi_init(112)...: 
(unknown)(): Other MPI error
```

Also in my output file "vasp.out", it reads `Initpm: Error in MPI_init `for 54 times. 

### Steps to reproduce

```Shell
open a tmux session, and then run 'tmux.sh' to request an interactive node, and then run the line 'srun -n 54 vasp_ncl > vasp.out' in the job file.
```

### Job Submission Script

```bash
srun -n 54 vasp_ncl > vasp.out
```

### What I've tried

I'm thinking that it is some parallel problem since I have no issues running the same batch job in mpirun scripts on normal nodes.

**Comment by awadell1** [comment]
Few questions:
- Did you load the mpi module? `module load openmpi`? Or if you did something equivalent, what was that?
- What are the contents of `tmux.sh`?
- What do you mean by "normal nodes" in the "What I've tried section"?

Have you looked at our [MPI on Arjuna Documentation](https://arjunacluster.github.io/ArjunaUsers/about/user_software.html#mpi)? We don't currently support running MPI within an interactive job. I'm not sure exactly what `tmux.sh` is doing, but you might be hitting this limitation.

**Comment by jtcrystal** [comment]
- I just tried loading the mpi module, and I'm currently using `openmpi/4.1.3`.

- The following is my `tmux.sh` contents.

```
#!/bin/bash
salloc -J workflow -N 1 -n 54 -p cpu --mem-per-cpu 0 --time=7-00:00:00

```

- My wordings are unclear. What I meant by "normal" is that the task can be run normally if I use `mpi` command without any interactive sessions involved, but once I request an interactive session and try to use `srun` command, I will get the above MPI error.
- Instead of directly running the line `srun -n 54 vasp_ncl > vasp.out`, I also tried to write a script as below and run `bash run.sh` in the interactive session but still got the same MPI error message. 

"run.sh" script content
```
#!/bin/bash 
#SBATCH -J workflow  # Job name 
#SBATCH -n 54 # Number of total cores
#SBATCH -N 1  # Number of nodes 
#SBATCH --mem-per-cpu=1000 # Memory pool for all cores in MB 
#SBATCH -o std.out 
#SBATCH -p cpu
#SBATCH -A marom 
srun -n 54 vasp_ncl > vasp.out 

```
- Do you think it's possible to do with my .bashrc file? I remembered added a few spack load lines.

**Comment by jtcrystal** [comment]
Yes, I forget to mention, but I have tried adding `--mpi=pmix` to the script but nothing changes.

**Comment by awadell1** [comment]
How did you install vasp? Was it built against the current openmpi module ([It changed in May](https://lists.andrew.cmu.edu/mailman/private/arjuna-users/2022-May/000060.html))?

**Comment by awadell1** [comment]
Closing as stale
