### ISSUE TITLE
Node Down: All CPU nodes down

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#164]
If an open issue already exists for the node, please do not submit a duplicate!

Node:  d[001-002,004-024],f[002-010,012-017,019-024]
Date and Time you first noticed it was down: Reason=Node unexpectedly rebooted [slurm@2022-07-23T15:31:00]
Anything Else: Reason=Node unexpectedly rebooted [slurm@2022-07-23T15:31:00]

**Comment by yaomz16** [comment]
and BTW gpu nodes are down too, c015: Reason=Node unexpectedly rebooted [slurm@2022-07-23T15:27:10]

**Comment by awadell1** [comment]
And now we're all back online 🎉
