### ISSUE TITLE
Missing version `GLIBCXX_3.4.29' required by VASP to run

### ISSUE THREAD

**Issue by jtcrystal** [ArjunaCluster/ArjunaUsers#169]
### Your Name

JT WU

### Andrew ID

jiatian2

### Where it Happened

JobID: 235352 Nodes: d001

### What Happened?

When I run VASP, I immediately got the following error repeatedly in my std.out file,
`vasp_ncl: /home/jiatian2/software/anaconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by vasp_ncl)`,
and the job quitted right after. 

### Steps to reproduce

```Shell
sbatch run.sh
```

### Job Submission Script

```bash
#!/bin/bash 
#SBATCH -J workflow  # Job name 
#SBATCH -n 54 # Number of total cores
#SBATCH -N 1  # Number of nodes 
#SBATCH --mem-per-cpu=1000 # Memory pool for all cores in MB 
#SBATCH -o std.out 
#SBATCH -p cpu
#SBATCH -A marom 
mpirun -np 54 vasp_ncl
```

### What I've tried

I tried to update the gcc package with `conda install libgcc` and `conda install -c omgarcia gcc-6`, and the run `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/jiatian2/software/anaconda3/lib/`
The version I installed are libgcc-7.2.0 and  gcc-6-6.1.0. 

Then I looked up the version I got by `strings /lib64/libstdc++.so.6 | grep GLIBCXX` and got all the versions from GLIBCXX_3.4.1 to GLIBCXX_3.4.21 but not GLIBCXX_3.4.29.

**Comment by awadell1** [comment]
Glibc is part of the Centos7 distribution and will not be upgraded in the near future. Related: #113 

We recommend using [singularity](https://docs.sylabs.io/guides/3.5/user-guide/index.html) (Installable via spack) to containerize your app.

Alternatively, you could try manually compiling VASP; see here for a prior attempt by another user: #22
