### ISSUE TITLE
Updating google drive rclone backup

### ISSUE THREAD

**Issue by lancekavalsky** [ArjunaCluster/ArjunaUsers#186]
### Your Name

Lance

### Andrew ID

lkavalsk

### Where it Happened

n/a

### What Happened?

I previously followed the instructions in the documentation to setup `rclone` with google drive and have been successfully using it for data backup.

But, I just got the following email (which I can't make sense of) from Google saying I need to "migrate my impacted OAuth out-of-band flow to an alternative method"

How do you recommend I proceed?

> Hello Google OAuth Developer,
> 
> We're writing to remind you that the OAuth out-of-band (OOB) flow will be deprecated on October 3, 2022, to protect your users from phishing and app impersonation attacks.
> 
> What do I need to know?
> As we notified you in May and August 2022, any affected authorization endpoint requests will be blocked with an invalid_request error after October 3, 2022.
> 
> If you have already migrated your app(s) to an alternative OAuth method, no further action is required. Please note that if your app(s) is natively installed you may have to request your users to update the app to the newer version to stop using the OOB method.
> 
> Below are key dates for compliance:
> 
> September 5, 2022: A [user-facing warning message](https://notifications.google.com/g/p/AKWoLQiD6AlDY1xCsbIMmVWLgKHg2FwEe00hWQ1nhw8oKsHIvRQDn4Vgk4tGk7rSMYYgah5saPZCsP903IJ64yICv17WbcjLeJuVVbZL_S7CVT3rdiPuHOTJOTuBbUYr3GJvFZUCJnuz4lu-Nf0RNoG-RCy2ZeB_pfNYGKN6AA8KsbtayLdgni8) will be displayed to non-compliant OAuth requests.
> October 3, 2022: The OOB flow will be blocked for all clients and users will see the error page.
> Please reference our previous email with the subject line containing: “Migrate your OAuth out-of-band flow to an alternative method before October 3, 2022,” for more details.
> 
> What do I need to do?
> Please see the [Making Google OAuth interactions safer by using more secure OAuth flows blog post](https://notifications.google.com/g/p/AKWoLQjqaHFw6OC6geSESk7fxabQB3fPX2vOyyt9px7xKlU414Z9AiOPGBeW0tXXvc3Hh1s0LSS5U4wfwIzgjM2kyaPIXtebiJnoooqDAuk8nC15X_4qSoCSMQLwk5BRFTYE84jO3WvWoXfqahPWOf8a4qcECdWSOg) to learn about the deprecation
> Follow the [Out-of-band (OOB) Migration Guide](https://notifications.google.com/g/p/AKWoLQhYMgjS6rozZyXRXeHYtRrtYY-D94hG5okQD2ikglSRjXCQyCa1sMQN-pZEJ5ilNKRB5XTnD4r9rO-QbbyeNw8buF5yiBE9V5hnEgbzLj8A5Dg9sYC6kLs1cPj9kP3sLSKiYDlf7k70vqEMxcKPufyUF7YmFOtFgx3nmqcR) to migrate your app to an alternative method.
> You may acknowledge the upcoming deadline and suppress a possible user-facing warning message by following instructions in our blog post. All non-compliant authorization requests will be blocked with an invalid_request error when loading Google's OAuth 2.0 authorization endpoint after October 3, 2022.
> If necessary, you may request a one-time [deprecation enforcement extension](https://notifications.google.com/g/p/AKWoLQgXrNAqVuHQRgP8_rCWeCUP1jQvEBPeL9Sh8HVeujYDNG85T_5zrii9x-L_yNQ4wVqtG9RDL4tkRu2-IVubS0lprspH05niKoqPVlfwdutCLXBUyXhAL02QdX-IIlCNlTSaVJTU_C7eYm942wekjU8WVNGNfzra_4fjBdVUaLEuCXO8g_t327bdtJg1WR9boU7B4Pd4n3ivZh0nrBtvvWElW-kSdFIDsksDrbiKMR7JsSFsziN2PQ) for each listed OAuth client ID until January 31, 2023. For clarity, the enforcement for the OOB flow deprecation will be enforced on February 1, 2023 with no exceptions or extensions. If you have already requested an extension please ignore this instruction.

### What I've tried

I tried reading the links they provided in the email, but have no idea what any of it means...

**Comment by awadell1** [comment]
See: https://forum.rclone.org/t/google-oauth-migration-for-rclone/30545

We currently only provide rclone v1.56, just shy of the required v1.58. 

Moving forward:

1. Just use rclone’s client id (ie. Leave at the default and take the performance hit
2. Install v1.58 or later via spack and then reconfigure rclone
3. Wait for module providing rclone v1.59 and then reconfigure

I know @amalss18 and @hancheng2000, we're having some issues with their OAuth timing out after about a week. But I'm not sure if this is related or not

**Comment by amalss18** [comment]
I don't think anything needs to be done as long as you leave the app in "testing" as mentioned in the mail.

**Comment by awadell1** [comment]
@lancekavalsky Did it break?

**Comment by lancekavalsky** [comment]
looks like it is still working!! thanks
