### ISSUE TITLE
sbatch: error: spank: x11.so: Plugin file not found

### ISSUE THREAD

**Issue by CoopLo** [ArjunaCluster/ArjunaUsers#190]
### Your Name

Cooper Lorsung

### Andrew ID

clorsung

### Where it Happened

JobID: 251437
Node: e001

### What Happened?

Whenever I submit jobs I get the error "sbatch: error: spank: x11.so: Plugin file not found"

### Steps to reproduce

```Shell
sbatch error_submit.sh
```

### Job Submission Script

```bash
#!/bin/bash
#SBATCH -J test # Job name
#SBATCH -n 1 # Number of total cores
#SBATCH -N 1 # Number of nodes
#SBATCH -A barati
#SBATCH -p cpu
#SBATCH --mem-per-cpu=1000 # Memory pool for all cores in MB
#SBATCH -e RUN_NAME_%j.err
#SBATCH -o RUN_NAME_%j.out # File to which STDOUT will be written %j is the job #
#SBATCH --mail-type=END # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=clorsung@andrew.cmu.edu # Email to which notifications will be sent

echo "Job started on `hostname` at `date`"

echo " "
echo "Job Ended at `date`"
```

### What I've tried

1. I googled the error message and it appears to be an issue with how slurm is configured, which I do not have permissions to modify.
2. I tried running the command `scontrol show config | grep -i plugstackconfig` and it returns `PlugStackConfig         = (null)` which seems to indicate my environment doesn't see the job manager

**Comment by awadell1** [comment]
Support for the x11 plugin is not properly configured (The worker nodes don't have x11 installed). You can safely ignore this warning.

As this does not impact functionality, fixing it is not a priority.
