### ISSUE TITLE
Docker authentication

### ISSUE THREAD

**Issue by CoopLo** [ArjunaCluster/ArjunaUsers#191]
### Your Name

Cooper Lorsung

### Andrew ID

clorsung

### Where it Happened

JobID: N/A
Node: e001

### What Happened?

I do not appear to have proper authentication to run docker

### Steps to reproduce

```Shell
systemctl start docker
```

### Job Submission Script

```bash
N/A
```

### What I've tried

1. I tried adding `systemctl start docker` to a bash script which throws the error `Failed to start docker.service: Interactive authentication required.`
2. I also tried running docker in a bash script using `docker run -it [IMAGE]`, which throws the error `/var/spool/slurmd/job251440/slurm_script: line 16: docker: command not found`

**Comment by awadell1** [comment]
Access to the docker daemon is not provided by Arjuna, as it requires root access. Please see #138 for alternative options.

Please do not attempt to modify system services. Doing so can negatively impact system performance and would be a violation of the [Arjuna Acceptable Use Policy](https://arjunacluster.github.io/ArjunaUsers/about/accounts.html#acceptable-use-policy).

**Comment by CoopLo** [comment]
Thank you, this has been very helpful. I have gotten singularity installed with `spack install singularity`. It threw an error `Error: singularity-3.8.5-e4y6oztvutnvmbdfos77rbrchuksplbt: Package was not installed`, but I can start a singularity container and run the necessary scripts from inside the container now. It seems to be working fine.

However, when I try to run singularity in a bash script for job submission I get the following error: 

`/path/to/singularity: error while loading shared libraries: libseccomp.so.2: cannot open shared object file: No such file or directory`

I've tried explicitly adding `libseccomp.so.2` to the path in the bash script but that doesn't fix it. `echo $PATH` shows that `libseccomp.so.2` is indeed in my path, so I'm not exactly sure what's happening here. I tried adding `libseccomp.so.2` to the `SINGULARITYENV_LD_PATH` and that also didn't work. There are not many similar issues from what I've seen after some googling. Trying to use `singularity run` and `singularity exec` throw the same error so it leads me to believe this is an issue with singularity within the slurm submission process. Here's the script I'm running using `sbatch test_submit.sh`. 

```
#!/bin/bash
#SBATCH -J test # Job name
#SBATCH -n 1 # Number of total cores
#SBATCH -N 1 # Number of nodes
#SBATCH -A barati
#SBATCH -p cpu
#SBATCH --mem-per-cpu=1000 # Memory pool for all cores in MB
###SBATCH -e RUN_NAME_%j.err
#SBATCH -e RUN_NAME.err
###SBATCH -o RUN_NAME_%j.out # File to which STDOUT will be written %j is the job #
#SBATCH -o RUN_NAME.out # File to which STDOUT will be written %j is the job #
#SBATCH --mail-type=END # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=clorsung@andrew.cmu.edu # Email to which notifications will be sent

echo "Job started on `hostname` at `date`"

which singularity
export PATH="$PATH:/lib64/libseccomp.so.2"
echo $PATH

/home/clorsung/.local/bin/singularity shell meshdqn_ray.tar

echo " "
echo "Job Ended at `date`"
```

**Comment by awadell1** [comment]
Might want to try adding `spack load singularity` to your submit script.  That should set up your env correctly. 

FYI: worker nodes do not have the same image as the head node. Of it's not in the base CentOD image, related to slurm or loaded via a module, we don't provide it. For example, `/lib/libseccomp.so` may or may not exist on the workers.

Best,

Alex

**Comment by CoopLo** [comment]
Thank you for the help. It looks like singularity needs root privileges still when doing that. When I try that in my bash script I get `ERROR  : No setuid installation found, for unprivileged installation use: ./mconfig --without-suid`. 

I can get around this by installing from source as described [here](https://docs.sylabs.io/guides/3.5/admin-guide/admin_quickstart.html?highlight=mconfig). I modified the installation command to bypass any sudo commands as `./mconfig --prefix=/home/clorsung/SINGULARITY_INSTALL --without-suid && make -C builddir && make -C builddir install`. 

Once I have this, I am doing a test run this new singularity executable from command line as: `/path/to/singularity shell [IMAGE]` I get the error: `ERROR  : Failed to create user namespace: user namespace disabled`. Some googling says I need to modify namespace creation (I'm not familiar with namespaces in this context, so there could be a workaround I'm not aware of), which I don't have the permissions to do. [This](https://docs.sylabs.io/guides/3.6/admin-guide/user_namespace.html#user-namespace-requirements) seems to be saying this requires root privileges

If I run from my bash script I get the error: `FATAL:   while extracting meshdqn_ray: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found`. Strangely, I see that `unsquashfs` is at the path `/usr/sbin/unsquashfs`, but in the submission script this isn't found even though `/usr/sbin` is in the path. Is there any way to get `unsquashfs` to load in the bash script? It can't be loaded/installed through spack

**Comment by awadell1** [comment]
Did some more poking, and it looks like singularity is not user-installable. Plus, as it needs openssl@1.1.1, we will need to take Arjuna offline for the upgrade. Not sure when we'll do this, but we are interested in supporting this use case.

> Strangely, I see that unsquashfs is at the path /usr/sbin/unsquashfs, but in the submission script this isn't found even though /usr/sbin is in the path

Again, the worker's __are not the head node__, and do not have an identical set of software installed. It is not unexpected for things to not match up.

**Comment by awadell1** [comment]
Closing as Apptainer is installed
