### ISSUE TITLE
Jobs in queue

### ISSUE THREAD

**Issue by rfhari** [ArjunaCluster/ArjunaUsers#207]
### Your Name

Hariharan Ramasubramanian

### Andrew ID

hariharr

### Where it Happened

Job ID: 270849 to 270888

### What Happened?

I'm new arjuna user. I submitted my job yesterday night, but it seems to be still in queue (though marked priority). So I just want to double check if this the usual wait time or if there is some mistake on my end, while submitting the job.

**Comment by awadell1** [comment]
Yes. You've used roughly 10x your fair share allocation (see `sshare`) which has tanked your priority. 

You can see slurm's current estimate for your jobs start time with `scontrol show job id` where `id` is a job id
