### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#21]
Your Name:  "Archie" Mingze Yao
Your Andrew ID: mingzeya
Node(s) on which the problem occurred: c002
Expected Behavior: Job running normally
Observed Behavior: Failed at once 
Location of Log file Showing the Error:/home/mingzeya/Phase_field_project/multi_geometries/python_impl/all_constants_changed/case1/restart_at_epoch_45/restart_at_epoch_60/restart_at_epoch_115/restart_at_epoch_165/error_2997814.err
Location of Script showing [Minimum Working Example]:/home/mingzeya/Phase_field_project/multi_geometries/python_impl/all_constants_changed/case1/restart_at_epoch_45/restart_at_epoch_60/restart_at_epoch_115/restart_at_epoch_165/train.py

Please also attach any logs and the submission script to this issue.

I get the following error in the StdErr file: "slurmstepd: error: execve(): /tmp/slurmd/job2997814/slurm_script: No such file or directory"

If you are not a frequent github user, please also provide us with a contact email here:
Contact Email: amyao@cmu.edu

**Comment by awadell1** [comment]
Continuation of #20.
