### ISSUE TITLE
Error while compiling a solver

### ISSUE THREAD

**Issue by fujah06** [ArjunaCluster/ArjunaUsers#211]
I am trying to compile a server and got this error

[oajenifu@coe multiphaseInter]$ ./Allwmake
wmake phasesSystem
    ln: ./lnInclude
Making dependency list for source file VollerPrakash.C
Making dependency list for source file porousModel.C
Making dependency list for source file InterfaceCompositionModels.C
Making dependency list for source file interfaceCompositionModel.C
Making dependency list for source file multiphaseSystems.C
Making dependency list for source file multiphaseSystemNew.C
Making dependency list for source file multiphaseSystem.C
Making dependency list for source file phaseSystem.C
Making dependency list for source file orderedPhasePair.C
Making dependency list for source file phasePairKey.C
Making dependency list for source file phasePair.C
Making dependency list for source file phaseModels.C
Making dependency list for source file phaseModel.C
icpc -std=c++11 -pthread -fp-trap=common -fp-model precise -DOPENFOAM=2012 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-unknown-pragmas -diag-disable 327,654,1125,1292,2289,2304,11062,11074,11076  -O3 -Wl,-rpath,/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/platforms/linux64IccDPInt32-spack/lib -DNoRepository -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/finiteVolume/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/meshTools/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/thermophysicalModels/basic/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/thermophysicalModels/specie/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/thermophysicalModels/reactionThermo/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/thermophysicalModels/solidThermo/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/thermophysicalModels/solidSpecie/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/transportModels -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/transportModels/compressible/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/transportModels/incompressible/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/transportModels/interfaceProperties/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/transportModels/geometricVoF/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/TurbulenceModels/turbulenceModels/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/TurbulenceModels/compressible/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/TurbulenceModels/phaseCompressible/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/combustionModels/lnInclude -iquote. -IlnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/OpenFOAM/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/OSspecific/POSIX/lnInclude   -fPIC -c phaseModel/phaseModel/phaseModel.C -o Make/linux64IccDPInt32-spack/phaseModel/phaseModel/phaseModel.o
make: icpc: Command not found
make: *** [Make/linux64IccDPInt32-spack/phaseModel/phaseModel/phaseModel.o] Error 127

**Comment by amalss18** [comment]
Try loading gcc using `module load gcc`, before running `./Allwmake`

**Comment by fujah06** [comment]
for some reason the same error is still coming up

<pre>[oajenifu@coe multiphaseInter]$ ./Allwclean
wclean libso phasesSystem
wclean libso compressibleMultiPhaseTurbulenceModels
[oajenifu@coe multiphaseInter]$ module load gcc
[oajenifu@coe multiphaseInter]$ ./Allwmake
wmake phasesSystem
    ln: ./lnInclude
Making dependency list for source file VollerPrakash.C
Making dependency list for source file porousModel.C
Making dependency list for source file InterfaceCompositionModels.C
Making dependency list for source file interfaceCompositionModel.C
Making dependency list for source file multiphaseSystems.C
Making dependency list for source file multiphaseSystemNew.C
Making dependency list for source file multiphaseSystem.C
Making dependency list for source file phaseSystem.C
Making dependency list for source file orderedPhasePair.C
Making dependency list for source file phasePairKey.C
Making dependency list for source file phasePair.C
Making dependency list for source file phaseModels.C
Making dependency list for source file phaseModel.C
icpc -std=c++11 -pthread -fp-trap=common -fp-model precise -DOPENFOAM=2012 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-unknown-pragmas -diag-disable 327,654,1125,1292,2289,2304,11062,11074,11076  -O3 -Wl,-rpath,/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/platforms/linux64IccDPInt32-spack/lib -DNoRepository -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/finiteVolume/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/meshTools/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/thermophysicalModels/basic/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/thermophysicalModels/specie/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/thermophysicalModels/reactionThermo/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/thermophysicalModels/solidThermo/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/thermophysicalModels/solidSpecie/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/transportModels -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/transportModels/compressible/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/transportModels/incompressible/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/transportModels/interfaceProperties/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/transportModels/geometricVoF/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/TurbulenceModels/turbulenceModels/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/TurbulenceModels/compressible/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/TurbulenceModels/phaseCompressible/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/combustionModels/lnInclude -iquote. -IlnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/OpenFOAM/lnInclude -I/home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/intel-2021.7.1/openfoam-2012-ha5gksi34ei7svupj4luiwslql4cswb4/src/OSspecific/POSIX/lnInclude   -fPIC -c phaseModel/phaseModel/phaseModel.C -o Make/linux64IccDPInt32-spack/phaseModel/phaseModel/phaseModel.o
make: icpc: Command not found
make: *** [Make/linux64IccDPInt32-spack/phaseModel/phaseModel/phaseModel.o] Error 127

**Comment by awadell1** [comment]
Looks like you're missing `icpc` or intel’s C++ compiler; which we don't provide. 

Possible solutions:

1. Update your build script to use a compiler we do provide (gcc)
2. Install icpc. I'd recommend using spack, although you may need to use your own instance to provide a license file. Alternatively, Intel should have build/binaries available.

In the future, please use the Tech Support template for similar issues.

**Comment by fujah06** [comment]
Hi guys, since icpc has to do with the HPC, could you guys assist in installing it. I attempted it, but have not succeeded yet.

**Comment by abillscmu** [comment]
hey there's a spack-stage corresponding to the user `oajenifu` in `/tmp` that's using 9.2G of precious headnode root drive, can we get that cleaned up?

thanks

**Comment by amalss18** [comment]
Hey! So I spoke to someone who had installed OpenFOAM on Arjuna previously and he said that he was able to get it done using docker. I would suggest you try the same.

**Comment by amalss18** [comment]
> Hey! So I spoke to someone who had installed OpenFOAM on Arjuna previously and he said that he was able to get it done using docker. I would suggest you try the same.

Sorry, it looks like we don't have docker. Could you try following this and see if it works for you: https://qiita.com/daikumatan/items/1faf76ea37e4a6c15784

**Comment by fujah06** [comment]
Hi Amal, I have used that link before, the current issue is with compiler which I need ICPC install on the machine, but the provide gcc. the icpc I believe is in intel ONEAPI toolkit with the link below. So openfoam needs ICPC for it to build



https://www.intel.com/content/www/us/en/developer/tools/oneapi/hpc-toolkit-download.html?operatingsystem=linux


icx --version: no icx or icpc was found

Thanks for assistance.

**Comment by amalss18** [comment]
You can install `intel-oneapi-compilers` using spack as given in the tutorial. Then you should have both icpc and icx.

**Comment by fujah06** [comment]
For some reason, I did not see icpc and icx following the instruction
oajenifu@coe ~]$ spack install intel-oneapi-compilers %gcc@11.2.0
[+] /home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/patchelf-0.16.1-oomnbxlrkldes4pns3f43rvfwnh24rp6
[+] /home/oajenifu/.spack/opt/spack/linux-centos7-broadwell/gcc-11.2.0/intel-oneapi-compilers-2022.2.1-u3dn5tbby3xp55n7doj44imns5htmetx
[oajenifu@coe ~]$ spack load intel-oneapi-compilers
[oajenifu@coe ~]$ icx --version
bash: icx: command not found

**Comment by amalss18** [comment]
That's strange. This worked for me. What output do you get when you do `spack compiler find`?

**Comment by fujah06** [comment]
[oajenifu@coe ~]$ spack compilers
==> Available compilers
-- dpcpp centos7-x86_64 -----------------------------------------
dpcpp@2022.2.1

-- gcc centos7-x86_64 -------------------------------------------
gcc@11.2.0  gcc@8.2.0  gcc@4.8.5

-- intel centos7-x86_64 -----------------------------------------
intel@2021.7.1

-- oneapi centos7-x86_64 ----------------------------------------
oneapi@2022.2.1
[oajenifu@coe ~]$

**Comment by awadell1** [comment]
`/tmp/oajenifu` has been deleted.

Compiling tasks is compute work and **must be performed on the worker nodes** (See the [Acceptable Use Policy](https://arjunacluster.github.io/ArjunaUsers/about/accounts.html#acceptable-use-policy)). Arjuna uses the root file system to perform administrative tasks (i.e., job submission, system monitoring, and provisioning nodes). Excessive disk usage in `/tmp` compromises those operations.
