### ISSUE TITLE
unexpected error when submitting jobs

### ISSUE THREAD

**Issue by shangzhu-cmu** [ArjunaCluster/ArjunaUsers#212]
### Your Name

Shang Zhu

### Andrew ID

shangzhu

### Where it Happened

no job id since the submission failed

### What Happened?

I suddenly received this error when submitting jobs to Arjuna
`sbatch: error: Batch job submission failed: I/O error writing script/environment to file
`

note: my disk usage is under the quota limitation

### Steps to reproduce

1.submit the shell script, provided below, with 
`sbatch job.sh`
2.command output 
`
sbatch: error: spank: x11.so: Plugin file not found
sbatch: error: Batch job submission failed: I/O error writing script/environment to file
`

### Job Submission Script

```
#!/bin/bash
#SBATCH -J test # Job name
#SBATCH -n 1 # Number of total cores
#SBATCH -N 1 # Number of nodes
#SBATCH --gres=gpu:1
#SBATCH -A venkvis_gpu
#SBATCH -p gpu 
#SBATCH --mem-per-cpu=32000 # Memory pool for all cores in MB
#SBATCH -e infer_%j.err
#SBATCH -o infer_%j.out # File to which STDOUT will be written %j is the job #
#SBATCH --mail-type=END # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=shangzhu@andrew.cmu.edu # Email to which notifications will be sent

echo "Job started on `hostname` at `date`"
source activate wrapper_test

python test.py

echo " "
echo "Job Ended at `date`"
```

**Comment by abillscmu** [comment]
this was a result of the root dir being full. I've made a little space, should be resolved.
