### ISSUE TITLE
VASP installation on Arjuna

### ISSUE THREAD

**Issue by maituoy** [ArjunaCluster/ArjunaUsers#22]
Hi, I'm wondering if VASP can be installed as a module on Arjuna? Thank you

**Comment by abillscmu** [comment]
Yes! You can install to your home directory via `spack install`. It looks like vasp is available.

**Comment by maituoy** [comment]
I do see a vasp package with `spack list`. But when I try to load via `spack load vasp`, it says "Error: Spec 'vasp' matches no installed packages.". Would you mind elaborating more details about how to use it with spack? I also tried to install the vasp locally with `spack install vasp`. However, it ends up with "vasp has to be downloaded manually". So, if I have the package, how do I install it via spack? Thank you for your time!

**Comment by awadell1** [comment]
I'd recommend checking out the spack documentation: https://spack-tutorial.readthedocs.io/en/latest/

`spack load package` will fail unless the package has been installed (`spack find` will show you what is installed)

Do post the full output of `spack install vasp`

**Comment by maituoy** [comment]
I followed the instruction in the spack documentation as below 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/37908868/131533357-b79a757f-1930-46b5-8763-a92d75f58295.png">
But it seems it still can not fetch the `.tar` file locally. Here is the full output of `spack install vasp` 
<img width="897" alt="image" src="https://user-images.githubusercontent.com/37908868/131533652-2a0bc868-81ef-4e66-9c6e-5338d143a210.png">

**Comment by awadell1** [comment]
Do link to things like that: https://spack.readthedocs.io/en/latest/basic_usage.html?highlight=Non-downloadable#non-downloadable-tarballs

Things to check:
- Does spack see your mirror: `spack mirror list`
- What does spack see as your configs: `spack config blame mirrors`

If that doesn't flag the issue, I would try to create the mirror again with `spack mirror create` and read the mirror docs:
https://spack.readthedocs.io/en/latest/mirrors.html#mirrors

**Comment by maituoy** [comment]
Still not able to let spack fetching the package locally. The spack can see my mirror as follow:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/37908868/132912299-987a7a62-1202-48f7-b032-8848455a4131.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/37908868/132912375-4fe541a8-864e-48af-b131-62b09e3a33a8.png">
I believe `spack mirror create` only works for those packages can be fetched online.

I'm not sure if it's due to the unsuccessful clean process. Since I tried to clean the previous cache before installation, but got a warning as below. 
<img width="769" alt="image" src="https://user-images.githubusercontent.com/37908868/132912923-7ed16ab8-02ac-4bb9-8a63-27ba248935c8.png">

**Comment by awadell1** [comment]
I've deleted `/tmp/maituoy` can you try again?

**Comment by maituoy** [comment]
No luck. I'm trying to compile it myself instead of using spack. Is it possible to install an Intel fortran compiler on Arjuna? I did not find one on the spack list. I'm not sure if the `spack install intel` will include everything but I don't have the permission to give it a try.

**Comment by awadell1** [comment]
That's a bummer. Did spack give any helpful error messages? You might want to try: ‘spack install -v vasp’

Yes, you can install intel compilers with spack.

You do have permission to install additional software with spack. (I.e. ‘spack install intel’) it will just end up in your ~/.spack directory instead of the spack users’. You will also have to tell spack about the new compiler ( if you want to use it with spack); see the spack docs for more info 

If you're getting specific permission issues, please post the command and resulting output


Best,

Alex

**Comment by maituoy** [comment]
`spack install -v vasp` gives the same error as before. 
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/37908868/132929202-adb2db6a-18e4-4c7f-bf19-529f2927c417.png">

`spack install intel` results in a permission error as follow
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/37908868/132929258-bf9bdc57-02fe-4974-994c-e2319cce26cf.png">

Really appreciate your time!
Maituo

**Comment by abillscmu** [comment]
Looks like intel compilers require a license

**Comment by abillscmu** [comment]
This is a guess, but try installing vasp@5.4.4. The vasp in spack is 6.1.1 or something, so when you do spack install vasp and you have 5.4.4 as the tarball, it may be going to the latest version, trying to download, and failing

**Comment by maituoy** [comment]
I've tried that before. It did not work.

**Comment by abillscmu** [comment]
Yeah it's not working for me either

**Comment by maituoy** [comment]
I've compiled it myself. Thanks for all your help. I attached my make file below in case anyone on Arjuna would like to compile VASP.
[makefile.include_Arjuna.zip](https://github.com/ArjunaCluster/ArjunaUsers/files/7147115/makefile.include_Arjuna.zip)

**Comment by abillscmu** [comment]
Happy that you got it yourself, and thanks for trying! We're going to continue working on this behind the scenes, because it's much deeper than just VASP -- currently our spack is not properly recognizing mirrors, which means any software spack can't download can't be installed via spack rn.

**Comment by maituoy** [comment]
Actually I also tried to install `wannier90` via spack mirror and I think in that case mirror was able to be recognized. 
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/37908868/132934718-32ec0aa0-6eff-4020-9b52-5f958ec23d22.png">
I hope this extra data point may help a little bit.

**Comment by abillscmu** [comment]
Oh yeah thanks!
