### ISSUE TITLE
Plugin File Error when submitting jobs on Arjuna 

### ISSUE THREAD

**Issue by shagunmaheshwaricmu** [ArjunaCluster/ArjunaUsers#225]
### Your Name

Shagun Maheshwari

### Andrew ID

shagunm

### Where it Happened

Job was not created and failed on sbatch

### What Happened?

When submitting the job using sbatch the slurm commands fail to successfully create the job.
The sbatch gives the following errors:[
](sbatch: error: spank: x11.so: Plugin file not found)

when going to the directory /etc/slurm the plugstack.conf file requires x11.so as an optional configuration, however the x11.so file is not present in the /etc/slurm directory.

The bash script being used to run the job is also requesting usage of a gpu partition and the following error is also observed:[
](sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified)

### Job Submission Script

```bash
#!/bin/bash
#SBATCH -n 1
#SBATCH --mem=2G
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu
#SBATCH --cpus-per-task=2
#SBATCH --time=15
python mnist.py
```

**Comment by abillscmu** [comment]
Thanks for the report. The spank error isn't your issue, your issue is that you need to specify the correct account for the GPU partition, which should be `venkvis_gpu`
