### ISSUE TITLE
Connection to my account is not working

### ISSUE THREAD

**Issue by fujah06** [ArjunaCluster/ArjunaUsers#226]
### Your Name

Olabode

### Andrew ID

oajenifu

### Where it Happened

N/A

### What Happened?

Having issue to connect to the cluster using sftp://*********@arjuna.psc.edu
I have connected in the past
Will appreciate if you could help me to look into it.

**Comment by abillscmu** [comment]
Hi,

it looks like your password has expired, you probably need to log in and reset it. In any case, I am unable to reproduce, everything is up on our end.
