### ISSUE TITLE
compute node missing some libraries that are available on head node

### ISSUE THREAD

**Issue by abhipath90** [ArjunaCluster/ArjunaUsers#230]
### Your Name

Abhishek Pathak

### Andrew ID

apathak3

### Where it Happened

JobID: 303541
Nodelist: e001

### What Happened?

While running a program that I installed and created a private module for, I find the following error.

error while loading shared libraries: libicudata.so.50: cannot open shared object file: No such file or directory

I see that these libraries are installed on head node inside /lib64 but those are not installed on the compute node. I have verified this by running 
ldconfig -p | grep icu
in slurm script, and also by 
ls /lib64 

It appears that these libraries need installation on compute node.

### Steps to reproduce

```Shell
Running "ldconfig -p | grep icu" on head node will produce results but it will not produce any results on compute node.
```

### Job Submission Script

```bash
#!/bin/bash                                                                                             
##SBATCH --time=00:15:00                                                                                
#SBATCH --nodes=1                                                                                       
#SBATCH --ntasks-per-node=1                                                                             
#SBATCH --mem=2400                                                                                      
#SBATCH --job-name="test_almaBTE"                                                                       
#SBATCH --output=test.out                                                                               

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

module use --append /home/apathak3/mySoftware/modulefiles
module load almabte

module list
ulimit -s unlimited

#ls /lib64                                                                                              

ldconfig -p | grep icu

VCAbuilder AlN.xml
```

### What I've tried

I have googled the issue and found this page describing a similar issue.
https://stackoverflow.com/questions/57214330/error-while-loading-shared-libraries-libicuuc-so-50

**Comment by awadell1** [comment]
CUDA libraries are provided via modules or spack on the compute node. Use `module spider cuda` or `spack find cuda` to find our offerings.

In general, if your' not loading it via a module and it's not part of the base CentOS distribution, we don't provide it on the compute nodes.

**Comment by abhipath90** [comment]
Thank you Alex for the clarification. I got confused because the libraries
were available on the head node without loading the module. To be honest, I
didn't know what those libraries were. This is great help. Thanks again.

Regards,
Abhishek

**Comment by awadell1** [comment]
Glad I could help!
