### ISSUE TITLE
Accessing Arjuna

### ISSUE THREAD

**Issue by hmera5** [ArjunaCluster/ArjunaUsers#233]
### Your Name

Hilda Mera

### Andrew ID

hmera

### Where it Happened

Hello, I'm trying to access arjuna but I'm getting the error or message below. I access arjuna using my username which is replaced with username below when I use ssh:

ssh username@arjuna.psc.edu

Output/message error I get is provided below:
ssh: Could not resolve hostname arjuna.psc.edu: Temporary failure in name resolution

Thank you

### What Happened?

Hello, I'm trying to access arjuna but I'm getting the error or message below. I access arjuna using my username which is replaced with username below when I use ssh:

ssh username@arjuna.psc.edu

Output/message error I get is provided below:
ssh: Could not resolve hostname arjuna.psc.edu: Temporary failure in name resolution

Thank you

**Comment by awadell1** [comment]
Can confirm that arjuna is online and accessible so it's probably an issue with your connection. 

Have you worked through our connecting to arjuna docs: https://arjunacluster.github.io/ArjunaUsers/getting_started/connecting.html
