### ISSUE TITLE
Accessing GPU node in arjuna

### ISSUE THREAD

**Issue by rfhari** [ArjunaCluster/ArjunaUsers#234]
### Your Name

Hariharan Ramasubramanian

### Andrew ID

hariharr

### Where it Happened

while creating SBATCH script

### What Happened?

I'm a PhD student from Prof Alan McGaughey's lab. I've been using CPU nodes in arjuna for a while. But for first time, I was trying to setup a SBATCH script to run on GPU nodes. I realized that I am not sure about the gpu partition name for my lab. Can you please let me know what it is? Also, it would be really great if you can share any example sbatch script for GPU nodes.

**Comment by awadell1** [comment]
You use your `group_gpu` account. So for me that's `venkvis_gpu`

To see your accounts, use `sacctmgr show assoc format=account%20 user=$(whoami)`. For example:

```shell
-bash-4.2$ sacctmgr show assoc format=account%20 user=$(whoami)
             Account
--------------------
         venkvis_gpu
               admin
             venkvis
```

Unfortunately, your group does not have access to the GPU nodes. Please have your PI reach out to Prof. Viswanathan to get that setup.

We do not have an example GPU submission script, a PR to add it to our docs would be welcome. Alternatively, see https://slurm.schedmd.com/sbatch.html

**Comment by awadell1** [comment]
Your group now has access to the GPU partition on arjuna. Be sure to use the `alan_gpu` account when submitting to the GPU partition

**Comment by rfhari** [comment]
Yep, thanks!
