### ISSUE TITLE
New User Request

### ISSUE THREAD

**Issue by NiranjanCarnegie** [ArjunaCluster/ArjunaUsers#235]
### Andrew ID

nbhombe@andrew.cmu.edu

### Group Name

Alan McGaughey

### Are you subscribed to arjuna-users@lists.andrew.cmu.edu?

Yes, or I have requested access to the list serve

### I will not block emails from root@coe.psc.edu

Yes

### I have read and will abide by the Acceptable Use Policy.

Yes

**Comment by amalss18** [comment]
You can find the login details in your email.
