### ISSUE TITLE
Runining time upgrade

### ISSUE THREAD

**Issue by fujah06** [ArjunaCluster/ArjunaUsers#240]
### Your Name

Olabode

### Andrew ID

oajenifu

### Where it Happened

N/A

### What Happened?

My simulation takes long time to run, and becomes very slow when I restate after it automatically stopped after seven days. I will like to upgrade the time period the simulation can run for from 7 days to 30 days.

Thanks,
Olabode.

**Comment by awadell1** [comment]
Unfortunately, we can not support and increase to the max wall times. I would encourage you to try and figure out what's causing the slowdown post restart and fix that.

I know that seems like a simple request, but practically it creates a huge headache:

1. Longer wall times will increase the queue length, which we've found to be unpopular. 
2. System stability is simply not that good. Especially in the winter with frequent storms, we really can not in good faith offer run times that long.
3. It makes maintenance very tricky. Any cluster-wide maintenance typically requires draining the nodes, which take roughly the max wall time to complete. Increasing to 30 days, means we need to schedule maintenance 30 days out or more. 

I'm not aware of any computing resources with a max wall time of 30 days, either at PSC or via ACCESS. If anyone knows of one, please comment.

**Comment by fujah06** [comment]
Hi Alex, thanks for the explanation. I will further investigate what's causing the slowdown post restart. How about 20 days and if needed I can stop for maintenance.

**Comment by awadell1** [comment]
We will not be increasing the wall time.
