### ISSUE TITLE
Submitting jobs under Prof. McGaughey's account

### ISSUE THREAD

**Issue by shravangodse16** [ArjunaCluster/ArjunaUsers#244]
I need to run MD calculations as a part of Prof. Malen and Prof. McGaughey's project. For this, I want to submit jobs under Prof. McGaughey's account by specifying his account in the sbatch job file. However, I don't want to change my default account (venkvis and venkvis_gpu), which I want to use for Prof. Viswanathan's project.

**Comment by amalss18** [comment]
I've added you to the `alan` and `alan_gpu` accounts.
