### ISSUE TITLE
Arjuna is Offline (Unplanned Outage)

### ISSUE THREAD

**Issue by awadell1** [ArjunaCluster/ArjunaUsers#247]
Arjuna is currently offline (likely storm related), and we have disabled ssh access to the cluster while we return the nodes to service.

We will update this thread with more information as it becomes available.

Best,

The Arjuna Admin Team

**Comment by amalss18** [comment]
Arjuna will be down for this week (8/7-8/13). We hope to have it up and running sometime early next week.

Best,
Arjuna Admin team

**Comment by awadell1** [comment]
Arjuna is back online, but may go down again next week for preventative maintenance.

We encourage all users to verify their data integrity and restore from backups as needed. 

>Hi Everyone,
> 
> Arjuna is returning to service. The power outage at PSC resulted in some
> filesystem issues which took us some time to debug. There has been a very
> small amount of filesystem corruption for running jobs as a result of this
> event, however, *if you have not received a direct message from me, then
> all of your data should be fine (we believe only running jobs were
> affected). *However, this should serve as a reminder to constantly *back up
> your critical data*, especially given that the Viswanathan group is moving
> and maintenance is likely to take longer in the future.
> 
> Looking forward, again given that the Viswanathan group is moving this
> fall, we may go down again next week to do a bit of preventative
> maintenance since we will no longer have easy physical access to the
> cluster. We will update you if we do this.
> 
> Cheers, and Happy Computing,
> the Arjuna Admin Team
> [Source](https://lists.andrew.cmu.edu/pipermail/arjuna-users/2023/000069.html)

Instruction on [data backup](https://arjunacluster.github.io/ArjunaUsers/getting_started/data_backup.html) is available in our documentation.
