### ISSUE TITLE
slurm issue

### ISSUE THREAD

**Issue by kianpu34593** [ArjunaCluster/ArjunaUsers#253]
### Your Name

Kian

### Andrew ID

jiankunp

### Where it Happened

CPU and GPU node slurm submission

### What Happened?

When I use 
```
sbatch run.sh 
```
to submit my job. I got the following error message:
```
sbatch: error: spank: x11.so: Plugin file not found
sbatch: error: Batch job submission failed: I/O error writing script/environment to file
```
It was working fine minutes ago. I believe this is a problem just happened

**Comment by awadell1** [comment]
Fixed
