### ISSUE TITLE
Cannot login...Connection reset by peer

### ISSUE THREAD

**Issue by mbabar09** [ArjunaCluster/ArjunaUsers#254]
### Your Name

Mohammad Babar

### Andrew ID

mbabar

### Where it Happened

Cannot login into arjuna account.

### What Happened?

When I try to login,
`>> ssh -y mbabar@arjuna.psc.edu`
I get,
`kex_exchange_identification: read: Connection reset by peer`

**Comment by awadell1** [comment]
password needed to be reset
