### ISSUE TITLE
Batch job submission failed

### ISSUE THREAD

**Issue by lancekavalsky** [ArjunaCluster/ArjunaUsers#255]
### Your Name

Lance

### Andrew ID

lkavalsk

### Where it Happened

CPU submission

### What Happened?

When trying to submit a job I get the following error:

```
sbatch: error: spank: x11.so: Plugin file not found
sbatch: error: Batch job submission failed: I/O error writing script/environment to file
```

(This looks like it is the same error as in #253)

**Comment by amalss18** [comment]
Fixed.
