### ISSUE TITLE
Can't start kernels because of "no disk space error"

### ISSUE THREAD

**Issue by makazumah** [ArjunaCluster/ArjunaUsers#256]
### Your Name

Victor Azumah

### Andrew ID

vazumah

### Where it Happened

Headnode: Coe

### What Happened?

I tried to start a jupyter kernel and got the following error. "Failed to start the Kernel 'GPAW (Python 3.10.6)'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. ENOSPC: no space left on device"

Jupyter log has: originalException = Error: ENOSPC: no space left on device, open '/tmp/kernel-v2-63204t5EmQKUd45ho.json'
The file listed is empty.

### What I've tried

Checked my disk quota and I'm not over.

Googled the error and it requires admin management.

**Comment by amalss18** [comment]
Fixed.
