### ISSUE TITLE
Unable to request GPU on c014

### ISSUE THREAD

**Issue by amalss18** [ArjunaCluster/ArjunaUsers#257]
### Your Name

Amal Sebastian

### Andrew ID

asebasti

### Where it Happened

Node: c014

### What Happened?

Any job that you submit to c014 requesting a GPU(s) sits in the queue waiting for resources despite the node being IDLE, and has no active jobs on it.

If you submit a job without requesting for a GPU, it works fine and allots resources immediately.

### Steps to reproduce

```Shell
srun -p gpu -A venkvis_gpu --gres gpu:1 -N 1 --ntasks-per-node=1 --cpus-per-task=4 --mem=10G -w c014 --pty bash
```

**Comment by awadell1** [comment]
@amalss18 Can we close this?

**Comment by amalss18** [comment]
Yes, this is not an issue anymore. However I have not figured out why we ran into this problem or what fixed the issue. The node went started showing expected behavior on its own after a few days.
