### ISSUE TITLE
Unable to access Arjuna

### ISSUE THREAD

**Issue by Luo-Yiqun** [ArjunaCluster/ArjunaUsers#262]
### Your Name

Yiqun Luo

### Andrew ID

luo2

### Where it Happened

When I try to log in to Arjuna:

ssh luo2@coe.psc.edu

### What Happened?

It returns the following:

kex_exchange_identification: read: Connection reset by peer

**Comment by awadell1** [comment]
Arjuna's address isn't `coe.psc.edu`, see the docs for instructions on connecting: https://arjunacluster.github.io/ArjunaUsers/getting_started/connecting.html

**Comment by Luo-Yiqun** [comment]
Thanks so much.
