### ISSUE TITLE
CPU nodes stuck on drain

### ISSUE THREAD

**Issue by lancekavalsky** [ArjunaCluster/ArjunaUsers#263]
### Node Name

d[002,007,016-017],f[001,004]

**Comment by amalss18** [comment]
Investigating the issue. I'm keeping the nodes in maintenance for now, and will bring them back up when the issue is resolved.

**Comment by lancekavalsky** [comment]
A large number of CPU nodes (27) have again entered a drain state

`d[001,003,005-006,013-014,020-021,024],f[002,005-009,011-014,016-017,019-024]`

**Comment by amalss18** [comment]
Fixed.
