### ISSUE TITLE
Error while running Lammps

### ISSUE THREAD

**Issue by prottaymalakar-cloud** [ArjunaCluster/ArjunaUsers#264]
### Your Name

Prottay Malakar

### Andrew ID

pmalakar

### Where it Happened

jobID 852712
node d001

### What Happened?

I am getting this error at the std.err file at the ~\melt\ directory :

srun: error: spank: x11.so: Plugin file not found
/home/pmalakar/lammps/build//lmp: error while loading shared libraries: libfftw3.so.3: cannot open shared object file: No such file or directory
srun: error: d001: task 0: Exited with exit code 127

### Steps to reproduce

```Shell
conda activate LAMMPS
cd melt

export PATH=$PATH:/home/pmalakar/lammps/build/

sbatch test.sh
```

### Job Submission Script

```bash
#!/bin/bash
#SBATCH --time=48:00:00
#SBATCH --partition=cpu
#SBATCH --mem-per-cpu=2G
#SBATCH --nodes=1
#SBATCH --job-name=lammps_test
#SBATCH --output=std.out
#SBATCH --error=std.err



srun lmp -in in.melt -l lmp.out
```

**Comment by awadell1** [comment]
1. you need to setup your environment within the submission script not outside of it.
2. You can ignore the spank error. See #225
