### ISSUE TITLE
Cannot connect to Arjuna in VSCode with CMU VPN

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#268]
### Your Name

Archie

### Andrew ID

mingzeya

### Where it Happened

vscode Arjuna logging in 

### What Happened?

Whenever I tried to connect to Arjuna on my personal computer (off-campus with CMU full vpn connected), the output panel shows something like "[17:36:37.900] > Waiting for server log..." for hundreds and thousands of times, and then I got warning  from vscode that "The remote host may not meet VS Code Server's prerequisites for glibc and libstdc++". This is a new issue, I used the same method to log onto Arjuna last night without a problem. 

### What I've tried

I tried rm -rf .vscode_server but not working

**Comment by amalss18** [comment]
Check #267
