### ISSUE TITLE
New User Request

### ISSUE THREAD

**Issue by hongshuh** [ArjunaCluster/ArjunaUsers#270]
### Andrew ID

hongshuh

### Group Name

Amir Barati Farimani

### Are you subscribed to arjuna-users@lists.andrew.cmu.edu?

Yes, or I have requested access to the list serve

### I will not block emails from root@coe.psc.edu

Yes

### I have read and will abide by the Acceptable Use Policy.

Yes

**Comment by amalss18** [comment]
Please check your email (inbox/spam) for your account details.
