### ISSUE TITLE
Accessing Alumna's Folder

### ISSUE THREAD

**Issue by kevinlar2** [ArjunaCluster/ArjunaUsers#274]
I am searching for some data that was generated by an alumna of our group, and one of the very last places I have to check is her personal folder on Arjuna. Is there any way to grant me access permissions, now that she no longer has access to her account?

**Comment by awadell1** [comment]
Seeing as they're an alumnus, let's retire the old account and transfer access to the folder to you.

What to do:
- Send me an email (I should pop right up in CMU's directory) copying your PI, the former group member, and their PI (If different) requesting the account be transferred to you.
- I'd prefer to delete their `~/.ssh` folder before transferring to avoid potentially leaking their security keys. Please advise if you need those files as well and why. I will need affirmation from the former group member as well.

This will give you full access but will count against your [disk storage quota](https://arjunacluster.github.io/ArjunaUsers/about/hardware.html#storage). I imagine that won't be an issue, and regardless, you'll have ~7 days to relocate the data.

Why can't I just give you read access?
- I need affirmative consent from the former user, especially if sensitive information is there.
- Arjuna isn't appropriate for long-term data storage. If this data is important, it should be stored
