### ISSUE TITLE
Submitted issue but if failed

### ISSUE THREAD

**Issue by OmidMLdata** [ArjunaCluster/ArjunaUsers#275]
### Your Name

Omid

### Andrew ID

obaratif

### Where it Happened

Jobid: 911593

### What Happened?

I submitted bit it will failed in a second.
I have ran several batches with this format a year before but it fail right now.
It seems some problems happened with Arjuna.
Could you help me in this way?

### Job Submission Script

```bash
#!/bin/bash
#SBATCH -J OGM_100_3 # Job name
#SBATCH -n 54 # Number of total cores
#SBATCH -N 1 # Number of nodes
#SBATCH -A barati
#SBATCH -p cpu
#SBATCH --mem-per-cpu=2000 # Memory pool for all cores in MB
#SBATCH -e /home/obaratif/OGM_NaCl/100/3error_lammps.err
#SBATCH -o /home/obaratif/OGM_NaCl/100/3out_lammps.out
#SBATCH --mail-type=END,FAIL,BEGIN # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=obaratif@andrew.cmu.edu # Email to which notifications will be sent
#SBATCH -t 7-0:00
echo "Job started on `hostname` at `date`"
module load gcc/11.2.0
mpirun -np 54 /home/obaratif/lammps/src/lmp_mpi < desalination_3.input


echo " "
echo "Job Ended at `date`"
```

**Comment by awadell1** [comment]
Can you be more specific about "how it failed"? Please see the [issue template](https://github.com/ArjunaCluster/ArjunaUsers/blob/main/.github/ISSUE_TEMPLATE/user-support.yml) for the missing information (For example, what was the output?)

**Comment by OmidMLdata** [comment]
There was no output but I created in batch that send me the email related to fail or complete the project.
The only thing that i received was:
Slurm Job_id=911593 Name=OGM_100MPa_3 Failed, Run time 00:00:00, FAILED, ExitCode 1
Slurm Job_id=911598 Name=desalination_3 Failed, Run time 00:00:00, FAILED, ExitCode 1

**Comment by awadell1** [comment]
There also should be a output and error files (looks like you have it written to `/home/obaratif/OGM_NaCl/100/3out_lammps.out`) 

What's in that file?

FYI: I'd advise against using a fix error / output file as submitting multiple jobs will just overwrite each other, making debugging much harder

**Comment by OmidMLdata** [comment]
This line is used for creating log file from the process of running data in Arjuna or local computer. 
*.out and *.err are used only for checking the process not for running the Project.
I think it could not even read the batch file !
I will fail at once when Arjuna open the batch file!

**Comment by awadell1** [comment]
If you got an email, Arjuna read the batch files, and the job ran. An exit code of 1 means the script didn't run successfully.
Hopefully, the *.err and *.out files can shed some light on _what_ went wrong in the script.

**Comment by OmidMLdata** [comment]
Thank you for pointing this out but the problem is that I did not receive any information on those files (It did not create those files after I received fail message!).

**Comment by awadell1** [comment]
I'd resubmit one of these jobs, removing the ``e` and `-o` lines (so it's the default); without those files, it's not really possible to say what's going wrong.

If that doesn't work:
- Try running your script within an [interactive session](https://arjunacluster.github.io/ArjunaUsers/getting_started/srun.html) checking that each command does what you expect
- Reach out to your PI / group members for a more in-depth debugging session (I'm just a graduate student ;-)) 

I can say that people are successfully running MPI jobs and LAMMPS on Arjuna. If I had to guess, I'd suspect that not including `module load openmpi` or a mismatch between the MPI LAMMPs was built with and the one that's being loaded. But again, without the output files, I'm just guessing

**Comment by amalss18** [comment]
@OmidMLdata Can you confirm if you have created this directory `/home/obaratif/OGM_NaCl/100/`? Because if this does not exist the job will fail.

**Comment by OmidMLdata** [comment]
Thank you. I solved the problem. It was sth related to batch directory.
