### ISSUE TITLE
Errors on signing in to account

### ISSUE THREAD

**Issue by prakarshyadav** [ArjunaCluster/ArjunaUsers#28]
Your Name: Prakarsh Yadav
Your Andrew ID: pyadav
Node(s) on which the problem occurred: head node
Expected Behavior: After login I should be in my home directory
Observed Behavior: I end up as bash-4.2 and get the input/output error

When I try signing in to my account on Arjuna, I get the following lines of text (At the end of this issue):
Also instead of signing in to my user I sign in directly into bash-4.2 and I cannot run basic commands to get more info.

> -bash-4.2$ ls
> ls: cannot open directory .: Input/output error

I have gotten this error when I tried to remove a directory from my user's folder to clear up some space. Let me know if you need any more info.

>  Welcome to the ARJUNA computing cluster!
>
>  A list of available scientific software can be found by typing:
>     module avail
>
>  Information about the cluster can be found at
>   https://arjunacluster.github.io/ArjunaUsers/
>
>  Technical operations, problems, and administration:
>    https://github.com/ArjunaCluster/ArjunaUsers/issues/
>
>  News, Announcements and Outage Updates:
>    https://lists.andrew.cmu.edu/mailman/listinfo/arjuna-users
>
>  Arjuna currently has 1.7T free of 20T total storage available.
>  Please monitor your disk usage and remove unnecessary files.
>  To view your current disk usage run:
>     quota -s
>
>Configuring SSH for cluster access
>install: cannot change permissions of ‘/home/pyadav/.ssh’: Input/output error
>/usr/bin/cluster-env: line 21: /home/pyadav/.ssh/authorized_keys: Input/output error
>chmod: cannot access ‘/home/pyadav/.ssh/authorized_keys’: Input/output error
>/usr/bin/cluster-env: line 24: /home/pyadav/.ssh/config: Input/output error
>/usr/bin/cluster-env: line 25: /home/pyadav/.ssh/config: Input/output error
>/usr/bin/cluster-env: line 26: /home/pyadav/.ssh/config: Input/output error
>/usr/bin/cluster-env: line 27: /home/pyadav/.ssh/config: Input/output error
>chmod: cannot access ‘/home/pyadav/.ssh/config’: Input/output error
>Falling back on spack location to locate lmod -> Please notify an admin
>-bash: spack: command not found
>Unable to locate lmod -> Please notify an admin
>-bash: /home/spack/spack/share/spack/setup-env.sh: Input/output error
>-bash: /home/pyadav/.bash_profile: Input/output error

**Comment by yaomz16** [comment]
I have similar issues when I logged onto Arjuna:

mingzeya@arjuna.psc.edu's password: 
Last login: Tue Aug 31 13:28:51 2021 from cmu-secure-128-237-82-13.nat.cmu.net
  Welcome to the ARJUNA computing cluster!

  A list of available scientific software can be found by typing:
     module avail

  Information about the cluster can be found at
   https://arjunacluster.github.io/ArjunaUsers/

  Technical operations, problems, and administration:
    https://github.com/ArjunaCluster/ArjunaUsers/issues/

  News, Announcements and Outage Updates:
    https://lists.andrew.cmu.edu/mailman/listinfo/arjuna-users

  Arjuna currently has 1.7T free of 20T total storage available.
  Please monitor your disk usage and remove unnecessary files.
  To view your current disk usage run:
     quota -s
Configuring SSH for cluster access
install: cannot change permissions of ‘/home/mingzeya/.ssh’: Input/output error
/usr/bin/cluster-env: line 21: /home/mingzeya/.ssh/authorized_keys: Input/output error
chmod: cannot access ‘/home/mingzeya/.ssh/authorized_keys’: Input/output error
/usr/bin/cluster-env: line 24: /home/mingzeya/.ssh/config: Input/output error
/usr/bin/cluster-env: line 25: /home/mingzeya/.ssh/config: Input/output error
/usr/bin/cluster-env: line 26: /home/mingzeya/.ssh/config: Input/output error
/usr/bin/cluster-env: line 27: /home/mingzeya/.ssh/config: Input/output error
chmod: cannot access ‘/home/mingzeya/.ssh/config’: Input/output error
Falling back on spack location to locate lmod -> Please notify an admin
-bash: spack: command not found
Unable to locate lmod -> Please notify an admin
-bash: /home/spack/spack/share/spack/setup-env.sh: Input/output error
-bash: /home/mingzeya/.bash_profile: Input/output error

**Comment by awadell1** [comment]
Closing for #29
