### ISSUE TITLE
New User Request

### ISSUE THREAD

**Issue by jtcrystal** [ArjunaCluster/ArjunaUsers#41]
Please provide the following information:

Your Name: JT Wu
Your Andrew ID: jiatian2@andrew.cmu.edu
Your Advisor's Name: Noa Marom

**Comment by awadell1** [comment]
See: https://lists.andrew.cmu.edu/mailman/private/arjuna-users/2021-September/000051.html
Fill this out: https://docs.google.com/forms/d/e/1FAIpQLSeh-Gt5Zb5TRRJyth5lviCgwzRjjUhtQhhWs-4m7OcpNF4-iQ/viewform?usp=sf_link
