### ISSUE TITLE
GPU jobs failed due to slurm tmp file

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#46]
If you notice a performance issue on arjuna, please first search the existing issues and ensure that it has not been reported. If you notice a similar example, please comment on that issue. 

Please provide the following information to help us help you:

Your Name: Archie Mingze Yao
Your Andrew ID: mingzeya
Node(s) on which the problem occurred: c004
Expected Behavior: run normally 
Observed Behavior: failed at once 
Location of Log file Showing the Error:/home/mingzeya/Phase_field_project/multi_geometries/python_impl/all_constants_changed/case6/error_89.err 
Location of Script showing [Minimum Working Example]: /home/mingzeya/Phase_field_project/multi_geometries/python_impl/all_constants_changed/case6/TrainGPU.sh

**Comment by abillscmu** [comment]
add -w c002 and try it again

**Comment by yaomz16** [comment]
> add -w c002 and try it again

I tried to add #SBATCH -w c002 to the .sh file, and the job was pending because of "ReqNodeNotAvail, UnavailableNodes:c002"

**Comment by yaomz16** [comment]
I think this error "slurmstepd: error: execve(): /tmp/slurmd/job00089/slurm_script: No such file or directory" only happens on GPU nodes. I tried to submit jobs to cpu partition, nothing like this happens.

**Comment by abillscmu** [comment]
Can reproduce

**Comment by abillscmu** [comment]
This should be fixed as soon as nodes reboot -- give it half an hour or so
