### ISSUE TITLE
Does the account/partition name of gpu nodes changed?

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#47]
Your Name: Archie 
Your Andrew ID: mingzeya
Node(s) on which the problem occurred: c nodes
Expected Behavior: 
Observed Behavior: cannot submit jobs due to "Invalid account or account/partition combination specified"
Location of Log file Showing the Error:
Location of Script showing [Minimum Working Example]: /home/mingzeya/Phase_field_project/multi_geometries/python_impl/all_constants_changed/case6/TrainGPU.sh

Please also attach any logs and the submission script to this issue.

I tried to submit job to batch with the following .sh file (same as the scripts I used before arjuna downage)
"
#!/bin/bash 
#SBATCH -J 6AllConst # Job name 
#SBATCH -n 8 # Number of total cores 
#SBATCH -N 1 # Number of nodes 
#SBATCH -A gpu
#SBATCH -p gpu
#SBATCH --gres=gpu:2
#SBATCH --mem-per-cpu=2000 # Memory pool for all cores in MB 
#SBATCH -e error_%j.err 
#SBATCH -o out_%j.out # File to which STDOUT will be written %j is the job # 
...
"

However I get the following error:
"sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified"

**Comment by abillscmu** [comment]
yeah, it's `-A venkvis_gpu` now
