### ISSUE TITLE
GPU Job killed by no reason 

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#48]
Your Name:  Archie
Your Andrew ID: mingzeya
Node(s) on which the problem occurred: c002
Expected Behavior:
Observed Behavior: Job killed 
Location of Log file Showing the Error:
Location of Script showing [Minimum Working Example]: /home/mingzeya/Phase_field_project/multi_geometries/python_impl/all_constants_changed/case6

Description:
I tried to run the job both in the interactive mode and batch mode, it runs normally at first, but the job will be killed suddenly with the following error (in the interactive mode): 
"srun: error: c002: task 0: Killed
srun: Force Terminated StepId=120.0"
If submitted to the batch, the job will fail after ~30 mins with an empty StdErr file.

**Comment by abillscmu** [comment]
Can you give the exact command you gave for the interactive job?

e.g. did you `srun ... --pty bash` or did you do `srun ... something else`

My first suspicion is that you're getting killed by a cgroup

**Comment by yaomz16** [comment]
> Can you give the exact command you gave for the interactive job?
> 
> e.g. did you `srun ... --pty bash` or did you do `srun ... something else`
> 
> My first suspicion is that you're getting killed by a cgroup

srun -J tmpInteractive  -A venkvis_gpu -p gpu -n 4 -N 1 --mem=8000 --gres=gpu:2 --pty bash

**Comment by yaomz16** [comment]
> Can you give the exact command you gave for the interactive job?
> 
> e.g. did you `srun ... --pty bash` or did you do `srun ... something else`
> 
> My first suspicion is that you're getting killed by a cgroup

Actually it doesn't matter whether I use interactive mode or batch mode, both will be killed

**Comment by yaomz16** [comment]
You can look through my directory "/home/mingzeya/Phase_field_project/multi_geometries/python_impl/all_constants_changed/case6", there are two StdErr files, both of them are empty. The two StdOut files only shows the start time of the job, however they didn't show the end time (I set it in the TrainGPU.sh file so that when the job ends, it will echo the end date), indicating that the job is terminated abnormally.

**Comment by abillscmu** [comment]
This has been resolved.

For anyone interested, we use a "Node Health Check" to periodically check the node's health. The NHC checks whether each process on the node is either (1) owned by root or (2) owned by the scheduler (slurm).  The NHC was incorrectly determining that we were using a different scheduler, and thus was killing all slurm processes when it was run.
