### ISSUE TITLE
Performance Issue: GPU jobs time limit only 1 day?

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#50]
Your Name:  Archie
Your Andrew ID: mingzeya
Node(s) on which the problem occurred: c nodes
Expected Behavior:
Observed Behavior:  TimeLimit=1-00:00:00 (according to the response of "scontrol show jobs JOB_ID")
Location of Log file Showing the Error: /
Location of Script showing [Minimum Working Example]: /

Hi, I wonder why the time limit for GPU jobs is only 1 day? I guess it is a mistake

**Comment by abillscmu** [comment]
This is expected behavior. The default time limit is one day. To change it you can use the -t flag. The max time limit is 14 days
