### ISSUE TITLE
Performance Issue: "Out-of-memory"

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#52]
Your Name: Archie 
Your Andrew ID: mingzeya
Node(s) on which the problem occurred: c002
Expected Behavior:
Observed Behavior: job killed abnormally 
Location of Log file Showing the Error: /home/mingzeya/CGCNN_project/AbNN_benchmark/hform/case1/error_191.err 
Location of Script showing [Minimum Working Example]:
/home/mingzeya/CGCNN_project/AbNN_benchmark/hform/case1/TrainGPU.sh

StdErr: "/var/spool/slurmd/job00191/slurm_script: line 28:  8156 Killed                  python3 main.py --prop hform --epochs 400 --lr_milestones 50 100 200 --gamma 0.25 --normalizing_const_AO 10000.0 --lr_generator 0.001 --lr_conv 0.001
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=191.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler."
There is no infomation printed by main.py in the StdOut file. 
It is the similar situation to use the interactive mode, the job will be killed with no reason, the following is the output on the screen:
"
...
Epoch: [0][415/1736]	 Loss 0.5844 MAE 0.6568 RMSE 0.7644
Epoch: [0][447/1736]	 Loss 0.5504 MAE 0.6353 RMSE 0.7419
Epoch: [0][479/1736]	 Loss 0.6319 MAE 0.5976 RMSE 0.7949
Epoch: [0][511/1736]	 Loss 0.5117 MAE 0.6075 RMSE 0.7153
Killed
(abnn) mingzeya@c002:~/CGCNN_project/AbNN_benchmark/hform/case1    $ 
"
Is it again something wrong with cgroup? Thanks!

**Comment by abillscmu** [comment]
This means that you exceeded the amount of memory you requested. Please request more memory.
