### ISSUE TITLE
Slurm error

### ISSUE THREAD

**Issue by kianpu34593** [ArjunaCluster/ArjunaUsers#53]
If you notice a performance issue on arjuna, please first search the existing issues and ensure that it has not been reported. If you notice a similar example, please comment on that issue. 

Please provide the following information to help us help you:

Your Name: Jiankun Pu
Your Andrew ID: jiankunp
Node(s) on which the problem occurred: 
Expected Behavior: Running 
Observed Behavior: Sbatch Error
Location of Log file Showing the Error: /home/jiankunp/gpaw_install_benchmark/spack_1st_install/sbatch_error.txt
Location of Script showing [Minimum Working Example]: /home/jiankunp/gpaw_install_benchmark/spack_1st_install/cpu_1_core.sh

Please also attach any logs and the submission script to this issue.

If you are not a frequent github user, please also provide us with a contact email here:
Contact Email:

[Minimum Working Example]: https://en.wikipedia.org/wiki/Minimal_working_example 

If you do not have any of the above, please explain why you do not have it, and submit the issue, however, the more information you give us, the better we can help you.

Below is the error message in sbatch_error.txt:
---------------------------------------------------------------------------
``
sbatch: error: resolve_ctls_from_dns_srv: res_nsearch error: Unknown host 
``
``
sbatch: error: fetch_config: DNS SRV lookup failed 
``
``
sbatch: error: _establish_config_source: failed to fetch config 
``
``
sbatch: fatal: Could not establish a configuration source 
``
Some other comments: 
I installed py-gpaw using a slurm enabled openmpi with this command
``spack install py-gpaw ^openmpi +pmi schedulers=slurm``
Will this affect slurm?

**Comment by abillscmu** [comment]
So, testing now to try and reproduce and be 100% confident, but I think what's happening is that spack is installing its own slurm. Then, when you have this gpaw module loaded, and you run a slurm command, it freaks out because it's a different slurm. This is not what we want. You need to configure it to use the system slurm if you go this route. But it's not an issue with the arjuna slurm.

I think you should use the system openmpi too BTW.

**Comment by abillscmu** [comment]
Confirmed this is what's happening. Therefore, this is actually expected behavior. 

You need to use the system slurm.
