### ISSUE TITLE
Performance Issue: launch failed requeued held

### ISSUE THREAD

**Issue by emilannevelink** [ArjunaCluster/ArjunaUsers#56]
If you notice a performance issue on arjuna, please first search the existing issues and ensure that it has not been reported. If you notice a similar example, please comment on that issue. 

Please provide the following information to help us help you:

Your Name: Emil Annevelink
Your Andrew ID: eannevel
Node(s) on which the problem occurred: Unknown
Expected Behavior: Job submits and runs the job file
Observed Behavior: Job goes into a pending state and is held waiting user intervention
Location of Log file Showing the Error: unknown
Location of Script showing [Minimum Working Example]: see current jobs 439 and 452. They were started using /home/eannevel/test_gpaw2/test_gpaw_1core.sh

If you do not have any of the above, please explain why you do not have it, and submit the issue, however, the more information you give us, the better we can help you.

**Comment by abillscmu** [comment]
I think we just need some reboots.

**Comment by abillscmu** [comment]
Yeah, so I noticed that this job was going to d013, checked the logs there, saw something that indicated we needed a reboot, and rebooted it. After I rebooted it, I was able to submit. 

Try adding -w c013 and it should go through.

**Comment by emilannevelink** [comment]
thanks! I can submit again :)
