### ISSUE TITLE
Wrong  System Time on worker nodes

### ISSUE THREAD

**Issue by mkphuthi** [ArjunaCluster/ArjunaUsers#66]
If you notice an issue on arjuna, please first search the existing issues and ensure that it has not been reported. If you notice a similar example, please comment on that issue.

> Please update the issue's title with something informative

Please provide the following information to help us help you:

## Basic Info
Your Name: Keith
Your Andrew ID: mphuthi

## Where it happened
Job Ids: 7331
Node(s) on which the problem occurred: f001

## What Happened
Expected Behavior: Expect ET
Observed Behavior: UTC reported

## Log Files
Location of Log file Showing the Error: /home/mphuthi/tests/time/job.sh.o7331
Location of Script showing [Minimum Working Example]: /home/mphuthi/tests/time/job.sh

Please also attach any logs and the submission script to this issue.

```log # 'log' here because it's a log file
Job started on f001 at Mon Sep 20 23:13:36 UTC 2021

Job Ended at Mon Sep 20 23:13:36 UTC 2021

```

```bash # 'bash' here it's a bash script
#!/usr/bin/bash

#SBATCH -n 1
#SBATCH -t 00-05:00
#SBATCH --mem=1000
#SBATCH -p gpu
#SBATCH -A venkvis_gpu
#SBATCH -N 1
#SBATCH -J job
#SBATCH -o job.sh.o%j

# The action:
echo "Job started on `hostname` at `date`"
echo " "
echo "Job Ended at `date`"
...

**Comment by abillscmu** [comment]
Is this actually causing an issue or is it just slightly annoying?

**Comment by mkphuthi** [comment]
It's not code breaking. I just refer to the time a lot to figure out when my jobs ran since some of job submission is automated.

**Comment by abillscmu** [comment]
It's fixed, but it won't take effect until reboot, and since it doesn't seem critical, I'm not going to force a reboot.
