### ISSUE TITLE
Required Node is Unavailable

### ISSUE THREAD

**Issue by emilannevelink** [ArjunaCluster/ArjunaUsers#67]
It looks like (from google) slurm sometimes puts "(ReqNodeNotAvail, UnavailableNodes:d[001-032],f[001-024])" if all the nodes are in use and sometimes pending/priority. Is this the correct way to interpret "ReqNodeNotAvail"?

Please provide the following information to help us help you:

## Basic Info
Your Name: Emil Annevelink
Your Andrew ID: eannevel

## Where it happened
Job Ids:
Node(s) on which the problem occurred: CPU nodes

## What Happened
Expected Behavior: Job is listed as priority or pending
Observed Behavior: (ReqNodeNotAvail, UnavailableNodes:d[001-032],f[001-024])

## What I've Tried

I looked at the current running jobs and observed all the nodes in use. I am more curious to know if this is the new method of knowing that your job is pending. I googled to see that this is sometimes the response of slurm but it could also mean that an admin needs to reset nodes.

**Comment by awadell1** [comment]
Yes, the nodes are draining to apply #66 and your job will resume when they are back.

Normally, you'd see resources or priority here (As the running jobs are all full node jobs, there isn't space regardless), but because of the draining flag you get this

https://slurm.schedmd.com/squeue.html#OPT_ReqNodeNotAvail

**Comment by prakarshyadav** [comment]
I have encountered this state of jobs today. If we observer the behavior: (ReqNodeNotAvail, UnavailableNodes:d[001-032],f[001-024])
Do we need to request a restart or just wait?
Also, is there a way for us to know whether the node is not responding (in need of admin reset) or just full with jobs?

**Comment by awadell1** [comment]
Look at sinfo
```shell
❯ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
cpu          up 7-00:00:00      1  fail* f005
cpu          up 7-00:00:00     12  down* d[004,006,013,018,026,029],f[003,012-013,018-020]
cpu          up 7-00:00:00     43    mix d[001-003,005,007-012,014-017,019-025,027-028,030-032],f[001-002,004,006-011,014-017,021-024]
gpu          up 14-00:00:0      9  drng@ c[002,004,008,010,016,024-027]
gpu          up 14-00:00:0      5  maint c[003,005,011,013,019]
gpu          up 14-00:00:0      3  fail* c[020-022]
gpu          up 14-00:00:0      1   drng c028
gpu          up 14-00:00:0      9    mix c[006-007,009,012,014-015,017-018,023]
debug*       up      10:00      2   idle e[001-002]
idle         up 7-00:00:00      2   idle e[001-002]
highmem      up 7-00:00:00      2   idle e[003-004]
```

The cpu nodes, are all in use (State of Mixed) or unresponsive and down (State of `down*`). The former means you should wait, the latter is something an admin needs to handle.

**Comment by abillscmu** [comment]
I just updated a bunch of nodes that were in drain, it's likely that that fixed this issue. Try it now. Also pls open new issues for stuff like this
