### ISSUE TITLE
Fair share policy

### ISSUE THREAD

**Issue by maituoy** [ArjunaCluster/ArjunaUsers#68]
Hi May I ask what is the current fair share policy on Arjuna? It makes no sense to me that two people from the same group (I assume they are from the same group since they used the same job name) are occupying all cpu nodes for several days.

**Comment by awadell1** [comment]
We use the Fair Tree Algorithm (https://slurm.schedmd.com/fair_tree.html) with billing based on cpu and memory utilization. The Half-Life Period is currently set to 2 days.

Long story short their FairShare is currently at 0.2 (See `sshare -l`), vs your FS of ~3. So priority-wise, your jobs will have ~15x the weight when slurm is picking who goes next. In the long run, it should come out in the wash; but we will monitor and adjust as needed.

That said if you have comments on how we could tweak the priority system (ie. which settings in slurm we should change), I'm all ears. Not saying it will happen, but I do think net throughput could be higher, and incentive structures tend to work.

**Comment by maituoy** [comment]
How does the effective usage change after the job termination? My concern is if the fairshare value won't be penalized for a long wall-time job. It could be possible that someone may request large amount of nodes in the same time and use them for 7 days. If the time needed to restore the fairshare value is less than the 7-day wall-time limit. Then in this way, people can occupy more computational time than they were supposed to.

**Comment by awadell1** [comment]
Fair share gets updated by the actual TRES utilization of the job. Yes, you can submit a large job and wait for your FS to recover and repeat. But in the longs run user utilization should line up with their FS shares. Right now we're definitely seeing some opportunistic utilization from users who got big jobs off fast, that should go down in the coming weeks. 

One thing we could do to fix this is add a priority penalty for larger jobs. This would encourage users to submit smaller jobs, and hopefully cut down on long wait times. Or setup QOS levels to limit the total cores a user can use at once.

As far as impact to you, what are you noticing? Longer wait times? Or something else?

**Comment by emilannevelink** [comment]
The queue is also draining. Since their jobs are so long, they are the only ones remaining on the queue and nobody else can submit until their jobs are done.

**Comment by awadell1** [comment]
Small Correction: The running jobs are full node jobs, so nobody would be running either way. Now we're just waiting for the jobs to run + a 15-minute reboot.

**Comment by maituoy** [comment]
Sounds like reasonable solutions. Yeah, I mean the wait time is much longer than expected. Hopefully, it will get resolved soon. Thanks for your clarification. Feel free to close the issue.
