### ISSUE TITLE
CPU Nodes Draining

### ISSUE THREAD

**Issue by venkkris** [ArjunaCluster/ArjunaUsers#69]
Node: All CPU nodes
Date and Time you first noticed it was down: Sep 21, 2021
Anything Else: 55 cpu nodes in draining; 1 cpu node (f005) fail. Unable to submit jobs to cpu nodes as a result.

Output from `sinfo`:

PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
cpu          up 7-00:00:00     55  drng@ d[001-032],f[001-004,006-024]
cpu          up 7-00:00:00      1  fail* f005
gpu          up 14-00:00:0     12  drng@ c[002,004,008-010,012,016,024-028]
gpu          up 14-00:00:0      5  maint c[003,005,011,013,019]
gpu          up 14-00:00:0      3  fail* c[020-022]
gpu          up 14-00:00:0      7    mix c[006-007,014-015,017-018,023]
debug*       up      10:00      2   idle e[001-002]
idle         up 7-00:00:00      2   idle e[001-002]
highmem      up 7-00:00:00      2    mix e[003-004]

**Comment by awadell1** [comment]
See:
- https://github.com/ArjunaCluster/ArjunaUsers/issues/67
- https://github.com/ArjunaCluster/ArjunaUsers/issues/66
