### ISSUE TITLE
QOS Max Memory Per User

### ISSUE THREAD

**Issue by emilannevelink** [ArjunaCluster/ArjunaUsers#70]
## Basic Info
Your Name:  Emil Annevelink
Your Andrew ID: eannevel

## Where it happened
Job Ids: 7838
Node(s) on which the problem occurred:

## What Happened
Expected Behavior: Job submission
Observed Behavior: Job submission holds with reason QOSMaxMemoryPerUser

I assume the root of the issue is that I was debugging an issue on the head node and the memory isn't releasing

## What I've Tried

Please List what you've tried to debug the issue. Please include commands and resulting output

1) I googled how to clear a users memory cache or releasing memory for a user
2) I looked for similar issues

> If you do not have any of the above, please explain why you do not have it, and submit the issue, however, the more information you give us, the better we can help you.

**Comment by awadell1** [comment]
Fixed, and thank you for submitting the issue. We had set a limit on user usage (Addressing #68 ) and I had expected the memory units to be in TRES not bytes.

The memory limitation has been reverted, there is still a limit of 1068 CPUs/user (Roughly 1/3 of the clusters CPUs).
