### ISSUE TITLE
New User Request

### ISSUE THREAD

**Issue by Moonrise55** [ArjunaCluster/ArjunaUsers#86]
### Andrew ID

ovinogra

### Group Name

Venkat Viswanathan

### Are you subscribed to arjuna-users@lists.andrew.cmu.edu?

Yes, or I have requested access to the list serve

### I will not block emails from root@coe.psc.edu

Yes

**Comment by abillscmu** [comment]
JFYI Olga you do need the VPN now and the herc backdoor no longer works, so not sure if you still have access
