### ISSUE TITLE
slurm_load_jobs error: Unable to contact slurm controller (connect failure)

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#92]
## Basic Info
Your Name: Archie
Your Andrew ID: mingzeya

## Where it happened
Job Ids: /
Node(s) on which the problem occurred: head node

## What Happened
Expected Behavior: type "squeue -u mingzeya" to see the status of my jobs 
Observed Behavior: get the error message "slurm_load_jobs error: Unable to contact slurm controller (connect failure)"

## Log Files
Location of Log file Showing the Error: /
Location of Script showing [Minimum Working Example]: /

**Comment by abillscmu** [comment]
Looks like the headnode rebooted. I will work on it when I get back to my computer.

**Comment by abillscmu** [comment]
I'm guessing PSC experienced some sort of power issue. In any case, this is resolved. Thanks for reporting it!
