### ISSUE TITLE
cannot kill job 56365

### ISSUE THREAD

**Issue by yaomz16** [ArjunaCluster/ArjunaUsers#93]
## Basic Info
Your Name: Archie
Your Andrew ID: mingzeya

## Where it happened
Job Ids: 56365
Node(s) on which the problem occurred: c024

## What Happened
Expected Behavior: kill it with "scancel 56365"
Observed Behavior: in CG status for at least 2 hours

## Log Files
Location of Log file Showing the Error: /home/mingzeya/Berkeley_LinLab/YuLong-HydroGel/change_temperature_4/310K/error_56365.err 
Location of Script showing [Minimum Working Example]: /

**Comment by abillscmu** [comment]
fixed via reboot of c024
