### ISSUE TITLE
add page for backup guidance

### ISSUE THREAD

**Issue by rkurchin** [ArjunaCluster/ArjunaUsers#95]
Could basically be a cleaned-up transcript of the little workshop/demo @abillscmu did on this awhile back, with links to how to set up endpoints on GDrive, Box, etc., run backups as cron jobs, etc.

I'm planning to set this up for myself this week so I can take some notes as I remind myself how to do it and can make a PR if you want them as seed material for this.

**Comment by abillscmu** [comment]
Would you mind converting your seed material into docs? We'd certainly like to incorporate this.

**Comment by rkurchin** [comment]
Yeah for sure, I'll try to cobble something together as I work on it for myself. May need supplement from you guys to cover cases I can't easily try out.

**Comment by abillscmu** [comment]
no problem. Thanks for helping out!
