### ISSUE TITLE
seff jobid giving connection refused error

### ISSUE THREAD

**Issue by emilannevelink** [ArjunaCluster/ArjunaUsers#97]
## Basic Info
Your Name: Emil
Your Andrew ID: eannevel

## Where it happened
Job Ids: 58415
Node(s) on which the problem occurred: head node

## What Happened
Expected Behavior: seff 58415 should give status of the completed job
Observed Behavior:

```
perl: error: slurm_persist_conn_open_without_init: failed to open persistent connection to host:localhost:6819: Connection refused
perl: error: Sending PersistInit msg: Connection refused
perl: error: Sending PersistInit msg: Connection refused
perl: error: DBD_GET_JOBS_COND failure: Unspecified error
Job not found.
```

## Log Files
Location of Log file Showing the Error: None
Location of Script showing [Minimum Working Example]: just command line

## What I've Tried

1) I looked for similar issues
2) I tried googling...

**Comment by abillscmu** [comment]
It's resolved temporarily but will take some admin work for a permanent fix. Thanks for the report!
