### ISSUE TITLE
SSH error: connection reset by peer upon login

### ISSUE THREAD

**Issue by DwaraknathT** [ArjunaCluster/ArjunaUsers#98]
## Basic Info
Your Name: Dwaraknath Gnaneshwar
Your Andrew ID: dgnanesh

## What Happened
Expected Behavior: Log in to arjuna after enabling VPN on in campus mode.
Observed Behavior: Tried to ssh into arjuna using `ssh dgnanesh@arjuna.psc.edu`
Getting the error -- `kex_exchange_identification: read: Connection reset by peer`

Help is much appreciated, thank you! Please also let me know if any info is required.

**Comment by abillscmu** [comment]
Use the "Full VPN" rather than the "Campus VPN"
